/* 委托与通牒内容库 —— 由内容设计生成 */
(function () {
  'use strict';

  window.BRIEFS = [

    /* ================= demand 事务要求 ================= */
    { id: 'b1', kind: 'demand', npc: 'su-wen', district: 'tower',
      title: '三天内交出一份名单',
      text: '苏纹把一份空白表格放进你的收件箱，标题是「本季度接口人清单」，截止栏写着三天后上午九点。她说董事会只要名字，不问理由，也不需要附件。表格背面用铅笔写了六个字：别全填真的。',
      days: 3,
      solve: { type: 'resource', need: { intel: 3 } },
      onSolve: { intel: 1, track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b2', kind: 'demand', npc: 'dai-siyuan', district: 'exchange',
      title: '把这个部门的预算砍掉三成',
      text: '戴思远把审计底稿推过来，第三页用红笔圈住合规组的差旅与耗材两项。他说这一刀必须你签，砍掉三成，留下来的两成算你替他们争的。签完把底稿还他，不要复印。',
      days: 4,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { money: 25, track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -3 } } },

    { id: 'b3', kind: 'demand', npc: 'yu-nanzhi', district: 'exchange',
      title: '收盘前平掉一笔对不上的账',
      text: '郁南枝说昨天的清算单多出一笔三十七万的尾差，来源栏填的是你的部门编号。她给你到今天收盘前的时间，用现金平掉，或者用一个说得过去的名字平掉。',
      days: 1,
      solve: { type: 'resource', need: { money: 40 } },
      onSolve: { track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 2 } },
      onRefuse: { track: { loyalty: -3 } },
      refuseLabel: '回绝' },

    { id: 'b4', kind: 'demand', npc: 'cheng-yan', district: 'lab',
      title: '补一份样本登记表',
      text: '程砚发来一条内部短讯，说三号柜的样本登记停在上周三，中间少了十一支。她不要你解释去向，只要求本周内把表补齐，扫码栏空着，签字栏也空着。',
      days: 4,
      solve: { type: 'resource', need: { intel: 2 } },
      onSolve: { intel: 2, gear: 1 },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b5', kind: 'demand', npc: 'peng-jian', district: 'lab',
      title: '把巡检记录补签回去',
      text: '彭戬把一叠巡检单拍在你桌上，说周二凌晨那趟无人值守缺了签名。他知道不是你值的班，但系统里挂的是你的编号，补签只要两分钟，笔就在他手里。',
      days: 2,
      solve: { type: 'stat', stat: 'stealth', dc: 12 },
      onSolve: { track: { power: 1, sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'b6', kind: 'demand', npc: 'tie-gui', district: 'docks',
      title: '交出工会的实到名单',
      text: '铁贵在码头办公室里点了根烟，说董事会要一份工会实到名单，用来核对罢工那天谁上了工。他把烟盒推给你，说名字他给，顺序要你来排。排错了算你的事。',
      days: 3,
      solve: { type: 'resource', need: { money: 30 } },
      onSolve: { intel: 2, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, renown: -1 } },
      onRefuse: { track: { renown: 2, loyalty: -2 } },
      refuseLabel: '不接这活' },

    { id: 'b7', kind: 'demand', npc: 'lao-ya', district: 'slum',
      title: '找回一份被撤下的旧档案',
      text: '老鸦说档案馆昨晚撤了一批编号，其中一份属于三年前那桩事故。他不问你为什么要，只问两件事：出多少钱，什么时候要。他说这东西在他手上留不过四十小时。',
      days: 2,
      solve: { type: 'resource', need: { money: 55 } },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'b8', kind: 'demand', npc: 'wen-duo', district: 'tower',
      title: '本周把季度汇报提前交上来',
      text: '闻铎在走廊里拦住你，说下周的董事会简报提前到周五，你那一页要在周四下班前放到他桌上。他说不要图表，不要附件，要能一次念完的话，念完他自己会补两句。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 13 },
      onSolve: { track: { loyalty: 3 } },
      onExpire: { track: { loyalty: -3, power: -1 } } },

    { id: 'b9', kind: 'demand', npc: 'wen-shicheng', district: 'orbit',
      title: '交出下个月的舱位分配表',
      text: '温仕成把一份手写的舱位表塞给你，说月台上有批货必须在表上，但收货人一栏不能出现。他要你以调度的名义重排一份正式版本，盖你部门的章，明天给他。',
      days: 3,
      solve: { type: 'district', district: 'orbit' },
      onSolve: { money: 20, intel: 1 },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b10', kind: 'demand', npc: 'yin-mian', district: 'docks',
      title: '让这批货的批文过期作废',
      text: '银面不露面，只让一个戴耳机的人把批文号念给你听。她说这批货三天后到港，你只要让它在系统里显示「已过期」，剩下的不用你管，也不要你出现在港区。',
      days: 3,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { money: 35, track: { sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'b11', kind: 'demand', npc: 'yu-ke', district: 'orbit',
      title: '补一份外来样本的入境申报',
      text: '雨客在通讯里说，有件东西在轨道港停了四天，货单是空的，温度记录只到第二天。他需要一份写得像样的申报，写清它从哪来、哪天进来的、由谁签收。',
      days: 4,
      solve: { type: 'resource', need: { intel: 4, chips: 1 } },
      onSolve: { intel: 3, track: { sin: 1, power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b12', kind: 'demand', npc: 'lu-wan', district: 'slum',
      title: '把一批药品的批号改掉',
      text: '陆晚说你上月送来的那批镇痛剂批号过期三个月，她已经用掉一半。她要你换一批新的批号单，或者干脆换一批药。她说她只问药，不问你怎么弄来的。',
      days: 2,
      solve: { type: 'resource', need: { money: 45 } },
      onSolve: { track: { renown: 2, sin: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2, loyalty: 1 } },
      refuseLabel: '不管' },

    /* ================= summon 高层传唤 ================= */
    { id: 'b13', kind: 'summon', npc: 'wen-duo', district: 'tower',
      title: '明天九点，董事会要见你',
      text: '闻铎的秘书打来电话，说董事会明天九点要听你本人讲那件事，通知上没有写议题。秘书提醒你三件事：正装、不带笔记、不带你的人。她说门禁只在九点前开一次。',
      days: 2,
      solve: { type: 'district', district: 'tower' },
      onSolve: { track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -3, power: -1 } } },

    { id: 'b14', kind: 'summon', npc: 'su-wen', district: 'tower',
      title: '日程被改到今晚十一点',
      text: '苏纹把你原本下周三的面谈直接挪到今晚十一点，地点在高塔四十七层的小会议室。她说时间不是她定的，你要是改期，下一次排在四个月后，而且不是同一批人见你。',
      days: 1,
      solve: { type: 'stat', stat: 'vitality', dc: 12 },
      onSolve: { track: { loyalty: 1, power: 1 } },
      onExpire: { track: { loyalty: -3 } } },

    { id: 'b15', kind: 'summon', npc: 'yu-nanzhi', district: 'exchange',
      title: '清算行听证，你必须在场',
      text: '郁南枝发出正式听证通知，编号抄送监事会，事项一栏写着「一笔路径不明的资金」。她提醒你，缺席会在记录里写成拒不配合，之后再想解释就得多带一个律师。',
      days: 2,
      solve: { type: 'district', district: 'exchange' },
      onSolve: { intel: 2, track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -3, sin: 1 } } },

    { id: 'b16', kind: 'summon', npc: 'dai-siyuan', district: 'exchange',
      title: '合规面谈，带着你的授权书',
      text: '戴思远约你周四下午做一次常规合规面谈，随信附了三页问题清单。最后一条写着：你是否曾绕过合规流程签发过任何一份文件。他建议你带上近三年的授权书副本。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 14 },
      onSolve: { track: { loyalty: 2, renown: 1 } },
      onExpire: { track: { loyalty: -3, sin: 1 } } },

    { id: 'b17', kind: 'summon', npc: 'cheng-yan', district: 'lab',
      title: '三号项目的评审要你签到场',
      text: '程砚说三号项目的阶段评审下周开，签字栏只有三个人，其中一个是你。她说你来不来都能开，但评审结论要不要算数，取决于那一栏有没有你的名字。',
      days: 4,
      solve: { type: 'district', district: 'lab' },
      onSolve: { intel: 2, gear: 1 },
      onExpire: { track: { loyalty: -2, power: -1 } } },

    { id: 'b18', kind: 'summon', npc: 'peng-jian', district: 'lab',
      title: '安保事故复盘，你要到场说明',
      text: '彭戬把最后一次通知发到你终端，说周四凌晨那起门禁事故要复盘，你被列在当事人名单里。他说他只负责通知，不负责解释这份名单是怎么排出来的。',
      days: 2,
      solve: { type: 'stat', stat: 'force', dc: 11 },
      onSolve: { track: { power: 1, loyalty: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b19', kind: 'summon', npc: 'lao-ya', district: 'slum',
      title: '灰市分账，要你本人到场',
      text: '老鸦说这次分账不去不行，场上有人点名要见你，见不到就把账本直接寄到高塔。时间定在后天凌晨，地点在下层旧水泵房，来时别带通讯设备。',
      days: 3,
      solve: { type: 'district', district: 'slum' },
      onSolve: { money: 30, track: { sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } },
      onRefuse: { track: { renown: -2, loyalty: -1 } },
      refuseLabel: '不去' },

    { id: 'b20', kind: 'summon', npc: 'yin-mian', district: 'docks',
      title: '码头七号仓，午夜见面',
      text: '银面托人带了一张泊位单，七号仓，午夜。背面写着两行字：带一份你签得起的授权，别带任何会记录的东西。泊位单上的日期是今天，过时不补。',
      days: 1,
      solve: { type: 'stat', stat: 'stealth', dc: 13 },
      onSolve: { intel: 2, track: { power: 1, sin: 1 } },
      onExpire: { track: { loyalty: -2, renown: -1 } } },

    { id: 'b21', kind: 'summon', npc: 'wen-shicheng', district: 'orbit',
      title: '引航局约谈，签发人是你',
      text: '温仕成说引航局要就上一批货物的签发人做一次问询，名单上有你的名字。他建议你亲自去，因为上次代签的那个人已经被先叫去谈过一次，回来之后不怎么说话了。',
      days: 2,
      solve: { type: 'resource', need: { money: 50 } },
      onSolve: { track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b22', kind: 'summon', npc: 'yu-ke', district: 'orbit',
      title: '穹顶外有人要跟你说话',
      text: '雨客说穹顶外侧的信号塔今晚会开一次窗口，对面要跟你说一句话，就一句。他说你可以不来，也可以迟到，但窗只开十九分钟，开完这一段轨道就归别人了。',
      days: 1,
      solve: { type: 'district', district: 'orbit' },
      onSolve: { intel: 4, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { loyalty: 2, renown: -1 } },
      refuseLabel: '不接这次通话' },

    { id: 'b23', kind: 'summon', npc: 'tie-gui', district: 'docks',
      title: '工会请你去码头讲一句话',
      text: '铁贵说工人后天上午在码头集合，只要一个人站上装卸台讲三句话，讲完就散，不喊口号，不递文件。他说这个人最好是你，因为你的名字还挂在集团编制上。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 13 },
      onSolve: { track: { renown: 3, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2, loyalty: 1 } },
      refuseLabel: '不去站台' },

    { id: 'b24', kind: 'summon', npc: 'lu-wan', district: 'slum',
      title: '你要来一趟诊所，当面',
      text: '陆晚只在终端上留了一行字：这周来一趟，别派别人。她说有些东西不能过任何线路传，包括你自己那份体检报告，也包括报告第三页上多出来的那两行。',
      days: 3,
      solve: { type: 'district', district: 'slum' },
      onSolve: { vitality: 1, track: { renown: 1, sin: -1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    /* ================= blood 血腥要求 ================= */
    { id: 'b25', kind: 'blood', npc: 'yin-mian', district: 'docks',
      title: '今晚要有一个人的名字从系统里消失',
      text: '银面说凌晨两点有一条船进港，名单上有个人不能下船。她把编号给你，说不用你动手，你只要让这个编号在今天之内不存在，交接单上会自己长出别的名字。',
      days: 1,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { money: 40, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } },
      onRefuse: { track: { renown: 1, loyalty: -2, sin: -1 } },
      refuseLabel: '不接' },

    { id: 'b26', kind: 'blood', npc: 'peng-jian', district: 'lab',
      title: '让那个值班员永远闭嘴',
      text: '彭戬说上周三凌晨有个值班员看见了不该看的画面。这个人现在还在所里上班，还在同一条走廊刷卡，工牌上的照片甚至换了新的。他给你两天把这件事结束。',
      days: 2,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { track: { power: 2, sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'b27', kind: 'blood', npc: 'wen-duo', district: 'tower',
      title: '一个编号今天必须作废',
      text: '闻铎没有解释这个编号是谁，只说是董事会的意思。他把一张纸推过来，上面只有一串数字和今天的日期。他说做完不要回话，也别让第二个人知道你见过这张纸。',
      days: 1,
      solve: { type: 'resource', need: { money: 80 } },
      onSolve: { track: { loyalty: 3, sin: 2 } },
      onExpire: { track: { loyalty: -3, sin: 1 } },
      onRefuse: { track: { loyalty: -3, renown: 1 } },
      refuseLabel: '这单我不做' },

    { id: 'b28', kind: 'blood', npc: 'yu-nanzhi', district: 'exchange',
      title: '把追债追到最后一步',
      text: '郁南枝说有个债务人三个月没露面，担保人还住在原来的地址，孩子在同一所学校。她要你让担保人明白，这笔账追的不是钱，追的是签名栏上那三个字。',
      days: 2,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { money: 45, track: { power: 1, sin: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b29', kind: 'blood', npc: 'lao-ya', district: 'slum',
      title: '处理掉一个不安静的线人',
      text: '老鸦说巷子里有个线人开始同时卖给两边，价格还越报越高，前天甚至报到了你的名字。他说这件事不收钱，他只问你哪天方便，因为这个人住的地方你熟。',
      days: 1,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { intel: 2, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 2, renown: -1 } } },

    { id: 'b30', kind: 'blood', npc: 'tie-gui', district: 'docks',
      title: '让罢工带头人今晚退场',
      text: '铁贵说工会里有人准备把谈判记录卖给董事会，开价不低，交接安排在明早。他给你一个班次和一条通道，说今晚这个人会独自走那条路，剩下的看你怎么想。',
      days: 1,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { track: { power: 2, sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } },
      onRefuse: { track: { renown: 2, sin: -1, loyalty: -1 } },
      refuseLabel: '放他走' },

    { id: 'b31', kind: 'blood', npc: 'yu-ke', district: 'orbit',
      title: '有个从穹顶外进来的人不能留记录',
      text: '雨客说昨天有个从外面进来的人，没有入境号，也没有体温记录，只有一张手写的过站条。这个人现在坐在轨道港候船区，两天后会有一班船停靠，那班船不查货。',
      days: 2,
      solve: { type: 'resource', need: { chips: 3 } },
      onSolve: { intel: 3, track: { sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'b32', kind: 'blood', npc: 'dai-siyuan', district: 'exchange',
      title: '让那个证人在问询前改口',
      text: '戴思远说下周有一场问询，关键证人提交的口供和物证对不上，时间差了两小时十七分。他要你在两天内让这份口供变得对得上，用什么方式他不指定。',
      days: 2,
      solve: { type: 'stat', stat: 'force', dc: 15 },
      onSolve: { track: { loyalty: 2, sin: 2 } },
      onExpire: { track: { loyalty: -3, sin: 1 } } },

    { id: 'b33', kind: 'blood', npc: 'cheng-yan', district: 'lab',
      title: '三号志愿者的名字要从名册上拿掉',
      text: '程砚说三号志愿者昨天出所之后没有再回来，名册上还留着签名，体检数据也还挂在系统里。她需要这个名字在今天之内从名册上消失，数据她自己会处理。',
      days: 1,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { gear: 1, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'b34', kind: 'blood', npc: 'wen-shicheng', district: 'orbit',
      title: '一个要跳船的人，别让他上船',
      text: '温仕成说今晚有一班船，票已经开出去了，持票人准备把同组三个人一起带走，连带一份不该出港的清单。他要你让这个人今天之内上不了任何一班船。',
      days: 1,
      solve: { type: 'resource', need: { money: 60 } },
      onSolve: { money: 20, track: { sin: 1, power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'b35', kind: 'blood', npc: 'su-wen', district: 'tower',
      title: '高塔今天多了一位不该出现的访客',
      text: '苏纹说访客登记里多了一个名字，登记时间是今天早上七点零四分，签入人一栏填的是你的工号。她给你到下班前的时间，让这个名字变回从没来过。',
      days: 1,
      solve: { type: 'stat', stat: 'stealth', dc: 13 },
      onSolve: { intel: 2, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'b36', kind: 'blood', npc: 'yu-nanzhi', district: 'exchange',
      title: '让那笔坏账彻底核销',
      text: '郁南枝说有一笔坏账在清算行挂了三年，账上的人早就不在了，只剩一个还在世的联系人每年寄一次函。她给你两天，让这笔账连同这个联系人的追索权一起终结。',
      days: 2,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { money: 55, track: { sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    /* ================= favor 人情托付 ================= */
    { id: 'b37', kind: 'favor', npc: 'lu-wan', district: 'slum',
      title: '帮她的病人弄一张合法身份',
      text: '陆晚说她手上有个人需要一份能过闸机的身份记录，年纪不大，伤口还没好，说话时不敢看人。她说她只有你一个能进系统的人，这件事不急，三天内都行。',
      days: 3,
      solve: { type: 'resource', need: { money: 35 } },
      onSolve: { track: { renown: 2, loyalty: -1, sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { sin: 1, renown: -1 } },
      refuseLabel: '帮不了' },

    { id: 'b38', kind: 'favor', npc: 'lao-ya', district: 'slum',
      title: '帮他把一个人从名单上留下来',
      text: '老鸦说下层的清理名单里有个人不该在上面，这人和他有点旧交情，早年替他挡过一刀。他不要你做什么大事，只要名单走流程的时候你多按一次暂停。',
      days: 2,
      solve: { type: 'stat', stat: 'charm', dc: 12 },
      onSolve: { track: { renown: 2, loyalty: -1, sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { renown: -2, sin: 1 } },
      refuseLabel: '不管这事' },

    { id: 'b39', kind: 'favor', npc: 'tie-gui', district: 'docks',
      title: '帮港区把被扣的工钱要回来',
      text: '铁贵说上个月有一笔工钱扣在集团账上，理由写在单子上，谁也看不懂，审批链停在一个已经不存在的岗位。他说工人不问理由，只问你什么时候能把钱放出去。',
      days: 3,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { track: { renown: 3, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2, loyalty: 1 } },
      refuseLabel: '不签这个字' },

    { id: 'b40', kind: 'favor', npc: 'yin-mian', district: 'docks',
      title: '帮一个人离港，不登记',
      text: '银面说她有个委托人要上今晚的货船，没有出境许可，也没有体检报告。她不付你钱，只记你这个人情，还说这种人情以后比钱值钱，比钱也贵。',
      days: 2,
      solve: { type: 'district', district: 'docks' },
      onSolve: { track: { power: 1, sin: 1, renown: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'b41', kind: 'favor', npc: 'yu-ke', district: 'orbit',
      title: '给穹顶外的人带一件东西出来',
      text: '雨客说外面有人需要一份纸质的、没有被任何系统记录过的东西。东西你自己挑，只要上面有你的签字或印章。他说收件的人认得你，不用写名字。',
      days: 3,
      solve: { type: 'resource', need: { money: 25 } },
      onSolve: { intel: 2, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 1 } },
      onRefuse: { track: { loyalty: 1, renown: -1 } },
      refuseLabel: '不带' },

    { id: 'b42', kind: 'favor', npc: 'wen-shicheng', district: 'orbit',
      title: '帮一个买不起票的人留个位子',
      text: '温仕成说有个常年在轨道港搬货的人，攒了两年钱还差一半，明年的名额就已经排完了。他说位子他能留一个，差额得有人补，这个人他推荐给你。',
      days: 3,
      solve: { type: 'resource', need: { money: 60 } },
      onSolve: { track: { renown: 3, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2, sin: 1 } },
      refuseLabel: '不垫这个钱' },

    { id: 'b43', kind: 'favor', npc: 'lu-wan', district: 'slum',
      title: '帮诊所弄一批能过审的耗材',
      text: '陆晚说诊所的耗材这个月被卡在审批上，清单里有一项她没法解释用途，写了三遍都被退回。她要你把它改成一个看起来合理的名字，剩下的表格她自己填。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { track: { renown: 2, sin: 1 } },
      onExpire: { track: { renown: -1, sin: 1 } } },

    { id: 'b44', kind: 'favor', npc: 'tie-gui', district: 'docks',
      title: '帮一个受伤的工人顶下这起事故',
      text: '铁贵说有个工人被卷进昨天那起事故，工牌记录的违规时间是他自己的名字，扣款单已经开出来了。铁贵要你在事故单上把责任挪到设备上，别挪到人身上。',
      days: 2,
      solve: { type: 'stat', stat: 'force', dc: 12 },
      onSolve: { track: { renown: 2, loyalty: -1, sin: 1 } },
      onExpire: { track: { renown: -2, sin: 1 } } },

    { id: 'b45', kind: 'favor', npc: 'lao-ya', district: 'slum',
      title: '帮他把一份档案递给该去的地方',
      text: '老鸦说手上有一份档案，正规渠道递不上去，卡在第二道签收就没了回音。他说只有你能让它落进某个不该进的收件箱。递上去之后，你就当没见过这份东西。',
      days: 3,
      solve: { type: 'district', district: 'slum' },
      onSolve: { intel: 3, track: { sin: 1, renown: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不递' },

    { id: 'b46', kind: 'favor', npc: 'yin-mian', district: 'docks',
      title: '帮她说服一个人，不要用刀',
      text: '银面说她的委托人准备今晚用更直接的方式解决一件事，已经把工具带上了。她说你只要能让他坐下来听你讲十分钟，这件事就不必有人受伤，也不必有人赔钱。',
      days: 2,
      solve: { type: 'stat', stat: 'charm', dc: 14 },
      onSolve: { track: { renown: 3, sin: -1, power: 1 } },
      onExpire: { track: { sin: 2, renown: -1 } } },

    { id: 'b47', kind: 'favor', npc: 'cheng-yan', district: 'lab',
      title: '帮她保下一个要被调岗的研究员',
      text: '程砚说组里有个研究员要被调去轨道港做记录员，理由是性格不适合团队协作，调岗单下周生效。她要你在单子上按一次退回，理由随便你写。',
      days: 3,
      solve: { type: 'resource', need: { intel: 3 } },
      onSolve: { track: { renown: 2, loyalty: -1, power: 1 } },
      onExpire: { track: { renown: -2 } } },

    { id: 'b48', kind: 'favor', npc: 'su-wen', district: 'tower',
      title: '帮她那天下午空出两个小时',
      text: '苏纹说她母亲那天要从穹顶外侧进来，手续都齐了，只差高塔的一趟电梯权限和一次访客确认。她要你把她下午的两个小时从日程里空出来，别人问起就说是会议。',
      days: 2,
      solve: { type: 'stat', stat: 'vitality', dc: 11 },
      onSolve: { track: { renown: 1, loyalty: 1 } },
      onExpire: { track: { renown: -1, loyalty: -1 } } },

    /* ================= trap 陷阱与试探 ================= */
    { id: 'b49', kind: 'trap', npc: 'dai-siyuan', district: 'exchange',
      title: '一份等着你签的谅解书',
      text: '戴思远把一份谅解书放在你面前，说你签了对大家都方便，上面写着你的部门自愿承担一次操作失误。他补充说，不签也行，这件事会按规定流程往下走一遍。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { track: { loyalty: 1, sin: 1 } },
      onExpire: { track: { loyalty: -2, sin: 2 } },
      onRefuse: { track: { renown: 1, loyalty: -2 } },
      refuseLabel: '不签' },

    { id: 'b50', kind: 'trap', npc: 'yu-nanzhi', district: 'exchange',
      title: '一笔送上门的短线',
      text: '郁南枝说有个渠道愿意让你用部门名义做一笔短线，收益归你，风险挂在部门账上。她说这个渠道平时不接中层，这次是有人替你说了一句话才破的例。',
      days: 2,
      solve: { type: 'fold', path: 'capital' },
      onSolve: { money: 70, track: { sin: 2 } },
      onExpire: { track: { sin: 1, loyalty: -2 } },
      onRefuse: { track: { loyalty: 1, renown: 1 } },
      refuseLabel: '不做这笔' },

    { id: 'b51', kind: 'trap', npc: 'wen-duo', district: 'tower',
      title: '一次提前的忠诚表态',
      text: '闻铎说监事会最近在做一次内部梳理，需要一批中层自愿提交近三年的联系人清单。他说提得早的人，名字会放在前面，提得晚的人，名字会放在另一个名单上。',
      days: 3,
      solve: { type: 'fold', path: 'control' },
      onSolve: { track: { loyalty: 2, sin: 1, power: -1 } },
      onExpire: { track: { loyalty: -2 } },
      onRefuse: { track: { renown: 1, loyalty: -2 } },
      refuseLabel: '不提交' },

    { id: 'b52', kind: 'trap', npc: 'su-wen', district: 'tower',
      title: '一次没有议题的会面',
      text: '苏纹说有人想在没有议题的情况下见你一面，地点在董事会那一层的一间空会议室，时间是明天中午。她说这个人你认识，而且你上次没有回他的消息。',
      days: 2,
      solve: { type: 'district', district: 'tower' },
      onSolve: { intel: 2, track: { sin: 1, power: 1 } },
      onExpire: { track: { power: -1, loyalty: -1 } } },

    { id: 'b53', kind: 'trap', npc: 'cheng-yan', district: 'lab',
      title: '一次免费的健康筛查',
      text: '程砚说研究所正在做一个免费筛查项目，参与者可以拿到一份完整的身体数据，还能换一笔不记名的补贴。名额只留给内部人，报名表上有一栏写着是否同意二次使用。',
      days: 3,
      solve: { type: 'stat', stat: 'vitality', dc: 12 },
      onSolve: { money: 30, vitality: -1, track: { sin: 1 } },
      onExpire: { track: { renown: -1 } },
      onRefuse: { track: { sin: -1, renown: 1 } },
      refuseLabel: '不去筛查' },

    { id: 'b54', kind: 'trap', npc: 'peng-jian', district: 'lab',
      title: '一次顺手的门禁授权',
      text: '彭戬说三号走廊今晚有一批设备要运出来，需要一份临时授权，用你的工号。他说东西不会出事，就算出了事也不会查到你头上，因为记录会跟着设备一起出园区。',
      days: 1,
      solve: { type: 'stat', stat: 'stealth', dc: 13 },
      onSolve: { gear: 2, track: { sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'b55', kind: 'trap', npc: 'lao-ya', district: 'slum',
      title: '一笔好得不真实的买卖',
      text: '老鸦说有人急着出一批货，价格是市价的三成，条件是要用你的名义过一手，货不落地，单据落地。他说他只赚介绍费，货和风险跟他一点关系都没有。',
      days: 2,
      solve: { type: 'resource', need: { money: 40 } },
      onSolve: { money: 65, track: { sin: 2, renown: -1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { renown: 1, sin: -1 } },
      refuseLabel: '不碰' },

    { id: 'b56', kind: 'trap', npc: 'tie-gui', district: 'docks',
      title: '一次举手之劳的放行',
      text: '铁贵说今晚有一辆车要从港区侧门出去，只装了一些废料，重量和单据都对得上。他说门岗那边只要一句你签的话，其余的他都安排好了，包括回来时的记录。',
      days: 1,
      solve: { type: 'fold', path: 'expand' },
      onSolve: { money: 35, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'b57', kind: 'trap', npc: 'yin-mian', district: 'docks',
      title: '一次不需要你出面的见面',
      text: '银面说她的委托人想认识你，不必见面，只要你把工牌放在某个位置十五分钟，位置在码头边上的寄存柜。她说这十五分钟里不会有任何人碰它，锁也是你锁的。',
      days: 1,
      solve: { type: 'stat', stat: 'intellect', dc: 14 },
      onSolve: { track: { power: 2, sin: 1 } },
      onExpire: { track: { power: -1, sin: 1 } },
      onRefuse: { track: { loyalty: 1, power: -1 } },
      refuseLabel: '不放下工牌' },

    { id: 'b58', kind: 'trap', npc: 'yu-ke', district: 'orbit',
      title: '一次来自穹顶外的馈赠',
      text: '雨客说外面有人托他带件东西给你，不重，也不值钱，只是一段刻在金属上的编号。他说收不收都行，只是收下之后要记着这个号，因为对面也会记着。',
      days: 3,
      solve: { type: 'stat', stat: 'stealth', dc: 12 },
      onSolve: { intel: 3, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 1 } },
      onRefuse: { track: { loyalty: 1, renown: -1 } },
      refuseLabel: '不收' },

    { id: 'b59', kind: 'trap', npc: 'wen-shicheng', district: 'orbit',
      title: '一次便宜的舱位',
      text: '温仕成说有一个长期空置的仓位最近放了折扣，只要报名就能锁住，付款可以延到入住当天。他说这种价位的名额很多人抢，他先来问你一句，别人还没通知。',
      days: 2,
      solve: { type: 'resource', need: { money: 70 } },
      onSolve: { track: { power: 1, renown: 1, sin: 1 } },
      onExpire: { track: { renown: -1 } },
      onRefuse: { track: { renown: -1 } },
      refuseLabel: '不锁' },

    { id: 'b60', kind: 'trap', npc: 'lu-wan', district: 'slum',
      title: '一次不用付钱的治疗',
      text: '陆晚说你这几个月的状态她都看在眼里，她可以给你做一次完整的修复，不收钱。条件是让她留一份完整的样本，包括血、组织，和时间戳，样本编号由她定。',
      days: 2,
      solve: { type: 'district', district: 'slum' },
      onSolve: { vitality: 2, track: { sin: 1 } },
      onExpire: { vitality: -1, track: { sin: 1 } },
      onRefuse: { vitality: -1, track: { renown: 1 } },
      refuseLabel: '不记录' },

  ];
})();
