/* 委托与通牒（第二批，60 条）。 */
(function () {
  'use strict';

  window.BRIEFS2 = [

    /* ================= demand 事务要求 ================= */
    { id: 'd1', kind: 'demand', npc: 'su-wen', district: 'tower',
      title: '排一份下周的会客顺序',
      text: '苏纹把一张会客日程推到你面前，说下周有三拨人要进高塔，董事会不想让他们碰面，顺序由你来排。她说这不是礼貌问题，是路径问题，周三上午之前交给她。表格下面她留了半行铅笔字：别按亲疏排。',
      days: 2,
      solve: { type: 'resource', need: { money: 40 } },
      onSolve: { intel: 1, track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'd2', kind: 'demand', npc: 'dai-siyuan', district: 'exchange',
      title: '补三个月前的培训签到',
      text: '戴思远说稽查下周会调上季度的合规培训记录，你们部门那一栏只有一次签到，日期还写错了一天。他要你在周一之前把三次签到补齐，笔迹别都一样，也别用同一种笔。他说这份顺序不进会议纪要，也不上系统。',
      days: 4,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -3 } } },

    { id: 'd3', kind: 'demand', npc: 'yu-nanzhi', district: 'exchange',
      title: '明天中午前把这两笔拆开',
      text: '郁南枝说有两笔同额度的转账在清算行被标成可疑，因为是同一天进出，而且同属一个楼层。她给你到明天中午，把其中一笔改走别的通道，手续费她出，单据要留痕但不能连号。她说尾号错一位就算两笔，两笔就是两个人来查。',
      days: 1,
      solve: { type: 'resource', need: { money: 45 } },
      onSolve: { track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 2 } },
      onRefuse: { track: { loyalty: -3 } },
      refuseLabel: '回绝' },

    { id: 'd4', kind: 'demand', npc: 'cheng-yan', district: 'lab',
      title: '把三号柜的温控记录补上',
      text: '程砚发来一条内部短讯，说三号柜周四凌晨断电四十分钟，记录里那一段是空的。她要求你在本周结束前补齐曲线，数值自己填，别填得太平。她说太平了看着像假的，她一眼就能看出来。她说她不想在伦理那一栏里看到空白。',
      days: 4,
      solve: { type: 'resource', need: { intel: 3 } },
      onSolve: { intel: 2, gear: 1 },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'd5', kind: 'demand', npc: 'peng-jian', district: 'lab',
      title: '换掉走廊尽头那只摄像头',
      text: '彭戬说二号走廊尽头那只摄像头角度偏了，照不到消防门，巡检报告上连着三次记了这一条。他要你在两天内把这条记录处理掉，或者把那扇门的开合次数改回正常值，两样随你挑。他说记录这种东西，改一次就要一直改下去。',
      days: 2,
      solve: { type: 'stat', stat: 'stealth', dc: 12 },
      onSolve: { track: { power: 1, sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'd6', kind: 'demand', npc: 'tie-gui', district: 'docks',
      title: '把夜班的排班表重排一遍',
      text: '铁贵把上周的排班表拍在桌上，说罢工那天有九个人的班次对不上考勤机。他给你三天，按他的口述重排一份正式的，别问为什么。他说问了也没用，那台机器那天下午确实坏过。他把那台考勤机的检修单也一起放在桌上。',
      days: 3,
      solve: { type: 'district', district: 'docks' },
      onSolve: { intel: 2, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, renown: -1 } },
      onRefuse: { track: { renown: 2, loyalty: -2 } },
      refuseLabel: '不接这活' },

    { id: 'd7', kind: 'demand', npc: 'lao-ya', district: 'slum',
      title: '到回收场取一只寄存箱',
      text: '老鸦说他有一只箱子寄在回收场，编号是手写的，只有他记得。他给你两天时间，用你部门的调拨单把它提出来。箱子里是什么他没说，只说别看，看完就不算他寄的了。他说箱子在四号堆场最里面那一排，锈得看不出编号。',
      days: 2,
      solve: { type: 'resource', need: { money: 55 } },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'd8', kind: 'demand', npc: 'wen-duo', district: 'tower',
      title: '周五前交两页风险说明',
      text: '闻铎在电梯里说，董事会要一份关于你们那条线的风险说明，两页，只写不利的那部分。他说不用掩饰，掩饰的东西他们看过太多，写清楚反而好交代，念完他自己会补两句。他说写完把稿子留在台上就行，别带走。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 13 },
      onSolve: { track: { loyalty: 3 } },
      onExpire: { track: { loyalty: -3, power: -1 } } },

    { id: 'd9', kind: 'demand', npc: 'xun-jie', district: 'ring',
      title: '把环带的巡检缺口补平',
      text: '荀戒在环带三十二号段截住你，说上个月那根支撑柱的巡检记录空了一段，空缺那天是他值的班。他要你在两天内补一条正常读数进去，或者代他签一次到场。他把记录本从腰带里抽出来，那一页折了一个角，说签的是他的名字。',
      days: 2,
      solve: { type: 'district', district: 'ring' },
      onSolve: { intel: 2, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'd10', kind: 'demand', npc: 'sa-er', district: 'salvage',
      title: '把回收场那批货挑出来',
      text: '萨尔说回收场新进了一批从穹顶外拉回来的东西，混在废钢里，编号早被磨掉了。她要你在三天内用调拨单把其中七件挑出来，单独堆在四号堆场。她说清单会给你，但别一次全给，分三次拿，每次少拿一件。',
      days: 3,
      solve: { type: 'resource', need: { money: 50 } },
      onSolve: { gear: 1, intel: 2, track: { sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'd11', kind: 'demand', npc: 'ban-tou', district: 'salvage',
      title: '把废料的重量重新登记',
      text: '班头把过磅单推过来，说昨天有一批废料出场时的重量和入库差了四百公斤，中间只经过你们的手。他给你两天，把差额平到合理区间，别平得太干净。他说查这个的人不识数，但会数小数点后面几位。他说数目这种东西，只要前后一致就没人细究。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { money: 30, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'd12', kind: 'demand', npc: 'wu-mian', district: 'memory',
      title: '补一张记忆柜台的交接单',
      text: '无面说记忆银行三号柜台的交接单少了一个签收时间，那段恰好没有监控。无面要你在本周内补上，具体到分钟，笔迹要像写字很慢的人。柜台外面排着长队，没有人说话，也没有人抬头看那台钟。无面把笔推过来，笔尖朝着自己那一侧。',
      days: 4,
      solve: { type: 'district', district: 'memory' },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    /* ================= summon 传唤 ================= */
    { id: 'd13', kind: 'summon', npc: 'wen-duo', district: 'tower',
      title: '董事会临时加了一场答辩',
      text: '闻铎说董事会临时加了一场答辩，明天下午两点，你一个人去，讲你们那条线这季度的差错。他说稿子不用带，带一张纸的提纲就行。他还说，进去之后他们问什么你答什么，别自己加。他把一支笔放在桌上，说这个借你。',
      days: 1,
      solve: { type: 'stat', stat: 'charm', dc: 14 },
      onSolve: { track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -3, power: -1 } } },

    { id: 'd14', kind: 'summon', npc: 'su-wen', district: 'tower',
      title: '今晚十点，日程多了一栏',
      text: '苏纹把你今晚的日程改动截图发过来，说十点那一栏是新加的，没有议题，也没有参会人名单，只有一间会议室的编号。她让你准时到，别带记录设备。她说她也不知道里面是谁，只知道是董事会直接排的。',
      days: 1,
      solve: { type: 'resource', need: { money: 35 } },
      onSolve: { intel: 3, track: { loyalty: 1 } },
      onExpire: { track: { loyalty: -2, power: -1 } } },

    { id: 'd15', kind: 'summon', npc: 'dai-siyuan', district: 'exchange',
      title: '合规面谈挪到今晚下班后',
      text: '戴思远把面谈通知塞进你的工位抽屉，时间改到今晚七点，地点从会议室挪到地下一层的小问询室。他说这次不谈流程，只谈上个月那两次授权是谁按的。他让你带授权书原件，复印件不算，他说纸上有没有指纹差别很大。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { track: { loyalty: 2 } },
      onExpire: { track: { loyalty: -3 } } },

    { id: 'd16', kind: 'summon', npc: 'yu-nanzhi', district: 'exchange',
      title: '清算行的复核要你亲自去',
      text: '郁南枝说周五上午有一场内部复核，清算行那边指名要签发人到场。她说你可以不带任何材料，人到了就行，但不到就会出现一条默认结论。她把时间写在你的手背上，用的是油性笔，说洗掉也得来。她说复核席上坐着的人不看材料，只看谁到了。',
      days: 2,
      solve: { type: 'district', district: 'exchange' },
      onSolve: { track: { loyalty: 2, power: 1 } },
      onExpire: { track: { loyalty: -3, sin: 1 } } },

    { id: 'd17', kind: 'summon', npc: 'cheng-yan', district: 'lab',
      title: '明早七点的评审要你到场',
      text: '程砚说三号项目的评审提前到明早七点，会场研究所地下二层，参会名单上写着你的工号。她说你不用准备，只用在签到场那一栏签个字。她把签到表翻到最后一页给你看，那一页只有三行格子。她说签完就能走，不用等散会。',
      days: 1,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { intel: 2, gear: 1 },
      onExpire: { track: { loyalty: -2, power: -1 } } },

    { id: 'd18', kind: 'summon', npc: 'peng-jian', district: 'lab',
      title: '安保事故复盘，明天上午',
      text: '彭戬说周一那起门禁误报开了复盘会，时间定在明天上午九点，安保线以外只有一个旁听位，给了你。他说旁听席不发言，但你坐的位置正对着记录员的镜头。他还说，坐姿别太随便。他说镜头后面的人会把你坐了多久记下来。',
      days: 2,
      solve: { type: 'resource', need: { gear: 1 } },
      onSolve: { intel: 2, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    { id: 'd19', kind: 'summon', npc: 'lao-ya', district: 'slum',
      title: '灰市分账，账房先生等你',
      text: '老鸦说下层那间洗衣房后屋今晚九点开分账，账房先生等着见你一面。他说这不是鸿门宴，是要你当面确认一个数，确认完这笔就算结了。他让你带现金去，别带卡，卡后面会留痕。他说这笔钱当面点清，出了这间屋就不算数。',
      days: 1,
      solve: { type: 'district', district: 'slum' },
      onSolve: { money: 35, track: { sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'd20', kind: 'summon', npc: 'tie-gui', district: 'docks',
      title: '码头七号仓，午夜前到',
      text: '铁贵传话过来，说午夜前十一点半在七号仓等你，只他一个人。他说这件事不上台面，你也别带人。仓里堆着还没清关的橡胶，味道很重，他说在那说话，外面听不见，里面也看不清脸。他说橡胶的味道能盖住烟味，也能盖住别的。',
      days: 1,
      solve: { type: 'stat', stat: 'force', dc: 12 },
      onSolve: { intel: 2, track: { power: 1, sin: 1 } },
      onExpire: { track: { power: -1, renown: -1 } } },

    { id: 'd21', kind: 'summon', npc: 'yin-mian', district: 'docks',
      title: '女术士的代理人约你一面',
      text: '银面说委托人愿意见你，时间是后天傍晚，地点在一艘没登记的小船上。她说船不会开，只停在泊位，见面不超过二十分钟。她还说委托人有个习惯，说话时喜欢用第三人称称呼自己，你别觉得奇怪。她说委托人只问一句话，问完就走。',
      days: 2,
      solve: { type: 'resource', need: { money: 30 } },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { intel: -1, track: { power: -1 } } },

    { id: 'd22', kind: 'summon', npc: 'yu-ke', district: 'outside',
      title: '穹顶外有人要见你一面',
      text: '雨客说外环那边有人想跟你说几句话，隔着气闸，不进来。后天下午气压窗口只有四十分钟，你得在第九道闸门外站着。他说不用带礼物，对方只想知道你上一次做决定时，先想到的是谁。他说对方不进门，你也不用出闸。',
      days: 2,
      solve: { type: 'district', district: 'outside' },
      onSolve: { intel: 3, track: { sin: 1, power: 1 } },
      onExpire: { intel: -1, track: { renown: -1 } } },

    { id: 'd23', kind: 'summon', npc: 'sa-er', district: 'salvage',
      title: '拾荒者的队伍要你去一趟',
      text: '萨尔说回收场那帮人这周不出工，起因是一张被压了两个月的配给单。她要你在三天内到堆场去，站在人群前面说一句话，说清那张单子什么时候能下来。她说他们不听文件，只听人。她说你站上去的时候他们不会鼓掌，只会安静。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 13 },
      onSolve: { track: { renown: 2, loyalty: -1 } },
      onExpire: { track: { renown: -2, loyalty: -1 } } },

    { id: 'd24', kind: 'summon', npc: 'wu-mian', district: 'memory',
      title: '记忆银行要你去核对一次',
      text: '无面递来一张通知，说有一份记录里的授权人写的是你的工号，需要你本人到柜台确认一次。时间约在四天后下午，无面说不用带证件，柜台认得人。柜台里那盏灯很白，坐下来之后没人会催你。无面说那天柜台只开一半，灯不会全亮。',
      days: 4,
      solve: { type: 'district', district: 'memory' },
      onSolve: { intel: 2, track: { loyalty: 1 } },
      onExpire: { track: { loyalty: -2, sin: 1 } } },

    /* ================= blood 血腥差事 ================= */
    { id: 'd25', kind: 'blood', npc: 'wen-duo', district: 'tower',
      title: '今晚有个人要从系统里消失',
      text: '闻铎说高塔十七层有个人手上有份不该外流的会议录音，人还在楼里。他给你到今天午夜，让这个人的门禁记录、工位访问、考勤三样同时断在今天之前。他说别做得干净，干净了反而像抹过。他说录音交出去之前，这个人还算是一个人。',
      days: 1,
      solve: { type: 'fold', path: 'purge' },
      onSolve: { intel: 2, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'd26', kind: 'blood', npc: 'yu-nanzhi', district: 'exchange',
      title: '把那个追债的人断在港区',
      text: '郁南枝说清算行有一笔账的追索权被一个人攥了三年，这人每季度寄一次函，最近开始去找记者。她给你两天，让这件事没有下一个季度。她说这人不是坏人，只是太有耐心。她说她会把信和笔一起收走，收得很干净。',
      days: 2,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { money: 60, track: { sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'd27', kind: 'blood', npc: 'dai-siyuan', district: 'exchange',
      title: '让那个稽核员提前病退',
      text: '戴思远说稽查组里有个人已经翻到去年那叠底稿，翻的速度比预期快了两周。他不要别的，只要这个人本周内离开岗位。他说方法随你，但手续上要像病退，像到人事那边挑不出毛病。他说病退这个说法最好用，因为它不需要解释。',
      days: 2,
      solve: { type: 'stat', stat: 'stealth', dc: 14 },
      onSolve: { track: { loyalty: 2, sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'd28', kind: 'blood', npc: 'peng-jian', district: 'lab',
      title: '把那个值班员调离这一层',
      text: '彭戬说监控室那个夜班值班员看见了不该看的一段，人没做错什么，就是嘴不太严。他给你到明天早上，让这个人不再出现在地下二层的班表上，用哪种方式他不问，只要周一之前不再见他。他说这人只是运气不好，撞在了那个时间点上。',
      days: 1,
      solve: { type: 'resource', need: { money: 50 } },
      onSolve: { track: { power: 1, sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'd29', kind: 'blood', npc: 'tie-gui', district: 'docks',
      title: '让罢工牵头人今晚退出',
      text: '铁贵说港口罢工那个牵头人今晚要在二号仓开个小会，会有十几个人去。他要你让这个会开不起来，也不用让他伤得多重，只要这几天站不起来。他说工人这块地他清楚，动手的分寸他知道，你只要把车开到位置。',
      days: 1,
      solve: { type: 'district', district: 'docks' },
      onSolve: { intel: 2, track: { sin: 2, power: 1 } },
      onExpire: { track: { sin: 2, renown: -2 } } },

    { id: 'd30', kind: 'blood', npc: 'lao-ya', district: 'slum',
      title: '处理掉一个不太安静的线人',
      text: '老鸦说下三层有个线人两头卖，上周把你们一次交接的时间说了出去。他说这人不用留，但也别做得太狠，留个能交代的说法就行。他把地址写在烟盒内侧，撕下来给你，说火里烧过就没人认得。他说下面的人换得快，少一个不会有人去数。',
      days: 2,
      solve: { type: 'stat', stat: 'force', dc: 13 },
      onSolve: { intel: 2, track: { sin: 2 } },
      onExpire: { track: { sin: 2, renown: -1 } } },

    { id: 'd31', kind: 'blood', npc: 'yin-mian', district: 'ring',
      title: '让一个人错过了那趟船',
      text: '银面说她的委托人今早改了主意，不想再让某个人离开这座城。她给你两天，让那人在登船前被拦下，方式不重要，只要上不了船。她说委托人原话是「她要留在这座城里，跟这里一起」。她说这是委托人的原话，她只负责转达。',
      days: 2,
      solve: { type: 'fold', path: 'control', need: 1 },
      onSolve: { track: { sin: 1, power: 2 } },
      onExpire: { track: { sin: 2, power: -1 } } },

    { id: 'd32', kind: 'blood', npc: 'wen-shicheng', district: 'orbit',
      title: '把那个没上船的记录抹干净',
      text: '温仕成说昨天凌晨有个人从轨道港的货梯下去，没有出境记录，也没过体检。这事上面今天已经开始查登船名单。他给你一天，把四号登船口七点前后的交接记录处理成设备故障，别留下一个人名。他说查到最后总要有一个原因，故障最省事。',
      days: 1,
      solve: { type: 'stat', stat: 'stealth', dc: 12 },
      onSolve: { money: 30, track: { sin: 1 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    { id: 'd33', kind: 'blood', npc: 'sa-er', district: 'salvage',
      title: '回收场那只手要处理掉',
      text: '萨尔说三号堆场那台压机这几天总卡，昨天清理的时候从料里挑出一只戴着手环的手。她说手环是登记过的。她给你两天，把这件事了结，别让它进任何一份事故报告。她说这块地她扫了八年，第一次不想扫。',
      days: 2,
      solve: { type: 'resource', need: { money: 40 } },
      onSolve: { intel: 2, track: { sin: 2 } },
      onExpire: { track: { sin: 2, renown: -1 } } },

    { id: 'd34', kind: 'blood', npc: 'xun-jie', district: 'ring',
      title: '把环带那个坠落记录改掉',
      text: '荀戒说上周环带有一处平台缺口，有人从那儿掉了下去，记录被写成检修期间无人通行。现在巡检员换班，那份记录还在。他给你两天，把它改成设备故障导致的坠落，责任人写设备编号，不写人。他说平台缺口的检修单他能补，现在缺的是一个名字。',
      days: 2,
      solve: { type: 'district', district: 'ring' },
      onSolve: { track: { power: 1, sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -1 } } },

    { id: 'd35', kind: 'blood', npc: 'wu-mian', district: 'memory',
      title: '把一段记忆提前结清掉',
      text: '无面说有一份记录的主人下周会来取，但柜台的排期已经把它移到了处理名单里。无面要你在两天内签字确认提前结清。无面说话时一直看着柜台后面的墙，说这是件让人不舒服的工作，签字的人通常不看。',
      days: 2,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { track: { sin: 2, loyalty: 1 } },
      onExpire: { track: { sin: 2, power: -1 } } },

    { id: 'd36', kind: 'blood', npc: 'cheng-yan', district: 'lab',
      title: '让那份样本来源查不下去',
      text: '程砚说伦理那边开始追问三号柜样本的来源人，问到这一步就有点近了。她要你在两天内让这条线断掉，方式由你，但别动研究所里的人。她说动了自己人就不好再往下了，这话说得很轻。她说这条线断在谁身上都行，别断在她组里。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 14 },
      onSolve: { intel: 2, gear: 1, track: { sin: 2 } },
      onExpire: { track: { sin: 2, loyalty: -2 } } },

    /* ================= favor 人情托付 ================= */
    { id: 'd37', kind: 'favor', npc: 'lu-wan', district: 'slum',
      title: '帮一个发烧的孩子躲过体检',
      text: '陆晚说她收了个发烧的孩子，烧退了但伤口还在，明天巡防要挨户做体检。她要你在明天中午前把孩子送进你名下一间空置的库房，门牌照常挂着不用的牌子。她说这次不用你出钱，只要你签一张临时占用单。',
      days: 1,
      solve: { type: 'resource', need: { money: 35 } },
      onSolve: { track: { renown: 2, loyalty: -1, sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { sin: 1, renown: -1 } },
      refuseLabel: '帮不了' },

    { id: 'd38', kind: 'favor', npc: 'yu-ke', district: 'outside',
      title: '给穹顶外的人送一箱药',
      text: '雨客说外环那边缺一批治烧伤的药，气闸只在后天傍晚开一次，东西得装在不保温的箱子里。他要你用维修物资的名义过一次申报，收件人写你们部门自己。他说送到就行，别问谁用，也别看开箱记录。他说药是用过的，箱子是空的，两边都不会细问。',
      days: 2,
      solve: { type: 'resource', need: { money: 45 } },
      onSolve: { intel: 2, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不送' },

    { id: 'd39', kind: 'favor', npc: 'wen-shicheng', district: 'orbit',
      title: '帮一个搬货的留住名额',
      text: '温仕成说轨道港那个常年在月台搬货的人，体检这关被卡住了，理由是肺功能边缘值。他要你以用人部门的名义出一份不需要体检的岗位说明，后天之前交到引航局。他说位子他留着，但只留到这一周结束。',
      days: 2,
      solve: { type: 'resource', need: { intel: 2 } },
      onSolve: { track: { renown: 2, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } } },

    { id: 'd40', kind: 'favor', npc: 'ban-tou', district: 'salvage',
      title: '帮班头把一个人的名字保住',
      text: '班头说回收场这季度要裁一批人，名单上有个老工人，手抖得厉害但没出过一次错。他要在三天内把这个人从裁撤名单挪到留用名单，理由栏空着也行。他说他自己填不了，他签的字从来没人认。他说那个人的手是抖的，但捡起的每一颗螺丝都是对的。',
      days: 3,
      solve: { type: 'stat', stat: 'charm', dc: 12 },
      onSolve: { track: { renown: 2, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2 } },
      refuseLabel: '不管这事' },

    { id: 'd41', kind: 'favor', npc: 'xun-jie', district: 'ring',
      title: '帮巡检员重抄一份承诺书',
      text: '荀戒说环带那起事故之后每个人都要补签一份安全承诺书，他那一份被组长退回来，说字太潦草。他要你替他重抄一遍，签名留白，明天上班前压在巡检站的抽屉里。他说这纸没别的用处，就是让人心里过得去。',
      days: 1,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { track: { renown: 1, power: 1 } },
      onExpire: { track: { renown: -1, loyalty: -1 } } },

    { id: 'd42', kind: 'favor', npc: 'lu-wan', district: 'slum',
      title: '帮诊所把那位病人送出城',
      text: '陆晚说诊所里那个人伤口已经能走路，但留在城里迟早被人认出来。她要在两天内弄到一张去轨道的长途票，用别的名字。她说钱她凑了一半，剩下的用手上的止血粉抵，那批粉是正规货，批号对得上。她说票根她会烧掉，烧完这事就当没办过。',
      days: 2,
      solve: { type: 'district', district: 'slum' },
      onSolve: { track: { renown: 2, sin: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { renown: -1, sin: 1 } },
      refuseLabel: '不掺和' },

    { id: 'd43', kind: 'favor', npc: 'lao-ya', district: 'slum',
      title: '帮老鸦把一封信递上去',
      text: '老鸦手上有一封信，走正规渠道会在第二道签收没回音。他要你在三天内让它落进稽查组的内部收件箱，别署名，也别转手。他说这信寄出去之后你就当从没见过，问他他也不认，问急了还会翻脸。他说这信是谁写的不重要，重要的是谁收。',
      days: 3,
      solve: { type: 'stat', stat: 'stealth', dc: 13 },
      onSolve: { intel: 3, track: { sin: 1, renown: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'd44', kind: 'favor', npc: 'tie-gui', district: 'docks',
      title: '帮港区家属把抚恤办下来',
      text: '铁贵说上个月港区那起事故，家属的抚恤卡在工伤认定上，因为死者的工牌那天没打卡。他要你在两天内让认定走完，材料他来补，你只需要在事故经过那一栏签个字。他说这钱等不起，家里有两个孩子。',
      days: 2,
      solve: { type: 'resource', need: { money: 30 } },
      onSolve: { track: { renown: 3, loyalty: -1 } },
      onExpire: { track: { renown: -2, sin: 1 } },
      onRefuse: { track: { renown: -2, loyalty: 1 } },
      refuseLabel: '不签这个字' },

    { id: 'd45', kind: 'favor', npc: 'yin-mian', district: 'docks',
      title: '帮她的委托人补一段经历',
      text: '银面说她那位委托人这周要办一次离港备案，可身份记录里有一段空白，正好是三年。她要你在三天内把那段空白填成一段普通的工作经历，公司名随便挑一家已经注销的。她说填得越普通越好，普通到没人记得。',
      days: 3,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { track: { power: 1, sin: 1, renown: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } } },

    { id: 'd46', kind: 'favor', npc: 'cheng-yan', district: 'lab',
      title: '帮她留下那台旧离心机',
      text: '程砚说研究所那台旧离心机下个月要按资产清算拉走，编号已经进了报废单。她要你在三天内把报废单退回一次，理由写账实不符。她说这台机器还能转，转得比新来的那台稳，稳的东西不应该先走。她说清算的人只认编号，不认转数。',
      days: 3,
      solve: { type: 'fold', path: 'control', need: 1 },
      onSolve: { track: { renown: 2, loyalty: -1, power: 1 } },
      onExpire: { track: { renown: -2 } } },

    { id: 'd47', kind: 'favor', npc: 'su-wen', district: 'tower',
      title: '帮她过闸机那天不登记',
      text: '苏纹说她母亲后天要从穹顶外侧进来做一次复查，手续齐全，只是不想让名字进高塔的访客系统。她要你在两天内安排一条不登记的内部通道，用员工临时授权。她说刷一次就够，出来的时候不用再刷。她说她母亲怕的不是规矩，是名单。',
      days: 2,
      solve: { type: 'stat', stat: 'intellect', dc: 12 },
      onSolve: { track: { loyalty: 1, renown: 1 } },
      onExpire: { track: { renown: -1, loyalty: -1 } } },

    { id: 'd48', kind: 'favor', npc: 'wu-mian', district: 'memory',
      title: '帮一份记录的主人留副本',
      text: '无面说有一份记录下周就要按流程销毁，主人是个上了年纪的维修工，家里人希望留一份纸质副本。无面要你在三天内走一次复印审批，编号写别的。无面说这算违规，但柜台里从来没有人问过这一栏。无面说这一栏从建行那天起就没人填过。',
      days: 3,
      solve: { type: 'district', district: 'memory' },
      onSolve: { intel: 2, track: { sin: 1, renown: 1 } },
      onExpire: { track: { sin: 1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不办' },

    /* ================= trap 试探 ================= */
    { id: 'd49', kind: 'trap', npc: 'wu-mian', district: 'memory',
      title: '一份白送的记忆清仓权限',
      text: '无面把一张盖好章的记忆清仓授权推到窗口边上，说到今天下班前有效，没人会回来核对。用它的条件是以后每次柜台盘点，你都要在备注里写一句「无异常」。无面说这只是让他们省点事，不是要你做什么。',
      days: 2,
      solve: { type: 'fold', path: 'control', need: 1 },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { track: { power: -1 } },
      onRefuse: { track: { renown: 1 } },
      refuseLabel: '把授权推回去' },

    { id: 'd50', kind: 'trap', npc: 'lu-wan', district: 'slum',
      title: '一位不用付钱的诊所常客',
      text: '陆晚说诊所近来多了一位常客，每次来都坐同一把椅子，走时留下一小包东西，说是还人情。她不肯拆，也不肯说是谁。她要你在三天内替她看一眼那包东西，如果她之后再提，就说你从没见过。她说那把椅子最近总是热的，但人走得很干净。',
      days: 3,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { intel: 3, track: { sin: 1, power: 1 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { renown: 1, loyalty: -1 } },
      refuseLabel: '不碰' },

    { id: 'd51', kind: 'trap', npc: 'wen-shicheng', district: 'orbit',
      title: '一张便宜到离谱的舱位',
      text: '温仕成说四号登船口有个位子空着，价格只要正常价的两成，明早六点半走。他说位子的原主上周临时不去了，手续都已经办完。他让你三天内决定，决定之前不要问那个人的名字，问了这单就作废。他说原主的手续齐全，只是人已经没了。',
      days: 3,
      solve: { type: 'resource', need: { money: 30 } },
      onSolve: { track: { power: 1, sin: 1 } },
      onExpire: { track: { renown: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不要这个位子' },

    { id: 'd52', kind: 'trap', npc: 'yu-ke', district: 'outside',
      title: '一份来自穹顶外的馈赠',
      text: '雨客把一个没有封口的袋子放在闸门内侧，说是外环那边托他带来的，不收钱。袋子里是一叠手写的纸条，字迹和你一位已经不在的同事一样。雨客说这不是他写的，他只是没问是谁写的。雨客说他没拆过，也不打算知道里面写的是什么。',
      days: 2,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { intel: 3, track: { sin: 1 } },
      onExpire: { intel: -1, track: { power: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不签收' },

    { id: 'd53', kind: 'trap', npc: 'ban-tou', district: 'salvage',
      title: '一本记着两套数的台账',
      text: '班头把回收场的进货台账推过来，说这上面有两套数，一套给上面看，一套他自己记。他给你三天时间去核一遍，核完把第二种记法教给他手下那个学徒。他说这孩子聪明，学东西快得让人不安。他说孩子学会之后，这本台账就该换一个封面了。',
      days: 3,
      solve: { type: 'stat', stat: 'intellect', dc: 13 },
      onSolve: { intel: 2, money: 25, track: { power: 1 } },
      onExpire: { track: { renown: -1, power: -1 } },
      onRefuse: { track: { renown: 1, loyalty: -1 } },
      refuseLabel: '不教' },

    { id: 'd54', kind: 'trap', npc: 'sa-er', district: 'salvage',
      title: '一只不该归你的旧手环',
      text: '萨尔说从废料里翻出一只手环，编号被磨掉一半，另一半还认得出，是你们部门去年发出去的。她说这东西她不打算上报，给你两天拿走，怎么处置随你。她还说这手环原本戴在一只手上，那只手现在也归你了。',
      days: 2,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { intel: 2, track: { sin: 2 } },
      onExpire: { track: { sin: 1, renown: -1 } },
      onRefuse: { track: { renown: 1, sin: 1 } },
      refuseLabel: '不接手环' },

    { id: 'd55', kind: 'trap', npc: 'yu-nanzhi', district: 'exchange',
      title: '一笔提前结清的陈年旧账',
      text: '郁南枝说有一笔三年前的账突然被结清了，付款方是一个已经不存在的部门，收款方是你。钱不多，来得干净，路径也对。她让你两天内确认一下这笔钱的性质，确认完就当作季度奖金入账，不用再提。她说这笔钱挂在账上，比拿在手上更显眼。',
      days: 2,
      solve: { type: 'resource', need: { money: 40 } },
      onSolve: { money: 45, track: { power: 1, sin: 1 } },
      onExpire: { track: { sin: 1, loyalty: -1 } },
      onRefuse: { track: { loyalty: 1, renown: 1 } },
      refuseLabel: '退回这笔钱' },

    { id: 'd56', kind: 'trap', npc: 'dai-siyuan', district: 'exchange',
      title: '一份没有署名的审计底稿',
      text: '戴思远把一叠审计底稿放在你桌上，说这是有人匿名递到他办公室的，前面三页写的是别人的事，第四页开始写你。他给你三天时间去认笔迹，认出来告诉他，认不出来就当没这回事。底稿他没有留复印件。',
      days: 3,
      solve: { type: 'stat', stat: 'intellect', dc: 14 },
      onSolve: { intel: 3, track: { power: 1 } },
      onExpire: { track: { loyalty: -2, renown: -1 } },
      onRefuse: { track: { loyalty: 1, sin: 1 } },
      refuseLabel: '不认领' },

    { id: 'd57', kind: 'trap', npc: 'peng-jian', district: 'lab',
      title: '一把没人会查的备用钥匙',
      text: '彭戬把一把地下二层冷库的备用钥匙放在你手边，说到下个月换锁前都没人会用这把。他说拿着它什么都不用做，只要不还回来。他还说冷库里存的东西最近换过一批，现在的比上个月那批轻，也安静。他说钥匙上的编号已经被磨掉了，认不出是哪一间。',
      days: 3,
      solve: { type: 'district', district: 'lab' },
      onSolve: { gear: 1, intel: 2, track: { sin: 1 } },
      onExpire: { track: { sin: 1, loyalty: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '把钥匙还回去' },

    { id: 'd58', kind: 'trap', npc: 'cheng-yan', district: 'lab',
      title: '一次不用登记的样本补录',
      text: '程砚说三号项目缺一组对照样本，正规流程要三周审批，她有办法当天补上，只要你在一张空白的入库单上先签字。她说这批样本来路干净，只是不想让它经过伦理那一关。她把签字笔横放在单子中间，没有催你。',
      days: 2,
      solve: { type: 'fold', path: 'purge', need: 1 },
      onSolve: { intel: 3, gear: 1, track: { sin: 1 } },
      onExpire: { track: { loyalty: -1, power: -1 } },
      onRefuse: { track: { loyalty: 1 } },
      refuseLabel: '不签这张单' },

    { id: 'd59', kind: 'trap', npc: 'xun-jie', district: 'ring',
      title: '一段可以随意填的巡检空档',
      text: '荀戒说环带那段巡检记录里有个四小时的空档，系统已经默认成设备维护，谁也不会去核对。他说这四小时你可以拿去办自己的事，只要在记录上按他的写法补一句「一切正常」。他说大家都是这么写的。',
      days: 2,
      solve: { type: 'fold', path: 'expand', need: 1 },
      onSolve: { intel: 2, track: { power: 1, sin: 1 } },
      onExpire: { track: { renown: -1 } },
      onRefuse: { track: { renown: 1, loyalty: 1 } },
      refuseLabel: '按实填写' },

    { id: 'd60', kind: 'trap', npc: 'wen-duo', district: 'tower',
      title: '一句可以替他说出口的话',
      text: '闻铎说下周董事会简报上有一句对你不利的话，他可以删掉，也可以换成另一句。换的那句会把责任挪到隔壁部门一个刚调来的人身上。他给你三天，让你自己决定要不要换。他说他不催，反正那天总要有人被念到。',
      days: 3,
      solve: { type: 'fold', path: 'control', need: 1 },
      onSolve: { track: { power: 2, sin: 1 } },
      onExpire: { track: { loyalty: -2 } },
      onRefuse: { track: { renown: 1, loyalty: 1 } },
      refuseLabel: '按原文念' },

  ];
})();
