/* NPC 个人支线 A 组。每人三幕：相识 / 交情 / 分晓。 */
(function () {
  'use strict';

  window.STORY_NPC_A = [

    /* ============ 闻铎 · 董事会监事 · 高塔商业区 ============ */
    {
      id: 'wd-1',
      npc: 'wen-duo',
      stage: 1,
      act: 1,
      district: 'tower',
      title: '闻铎：茶室里的第二次见面',
      text: '高塔四十九层的茶室只开到下午四点，窗外是永远不散的雾。闻铎把杯子推到你面前，茶早就凉了，他自己一口没喝。他问你上个月在三十三层走廊站了多久，语气像在核对一张表格。他说没有别的意思，只想确认你还记不记得那天闻到的味道。走廊尽头的电梯停了一下层，响了三声，门没开。',
      when: { minFolded: 1 },
      options: [
        { label: '把那天的时间报给他', relation: 2, run: { intel: 2, track: { loyalty: 1 } }, flag: 'wd_told_time' },
        { label: '反问他为什么查三十三层', relation: 1, run: { intel: 3, track: { loyalty: -1 } } },
        { label: '说那晚我没去过那里', relation: -2, run: { track: { sin: 1, loyalty: 1 } } },
      ],
    },
    {
      id: 'wd-2',
      npc: 'wen-duo',
      stage: 2,
      act: 2,
      district: 'tower',
      title: '闻铎：编号 J-1147 的复印件',
      text: '他把一只旧档案袋推过来，袋角磨得发白，封口只写了一行编号 J-1147。里面是三年前那场事故的原始签名页，收件人一栏被人涂掉了。他说这份东西在监事会走过七道流程，每一道都想让它消失。他要你确认那行被涂掉的名字，说完又补一句：你可以说没见过，也可以现在就走。',
      when: { minFolded: 5 },
      options: [
        { label: '帮他把涂掉的名字补上', relation: 3, run: { intel: 3, track: { loyalty: -1, power: 1 } }, flag: 'wd_helped' },
        { label: '问他拿什么换这份确认', relation: 0, run: { money: 50, track: { sin: 1, loyalty: -1 } } },
        { label: '把档案袋原样推回去', relation: -2, run: { track: { loyalty: 2, power: -1 } } },
      ],
    },
    {
      id: 'wd-3',
      npc: 'wen-duo',
      stage: 3,
      act: 3,
      district: 'tower',
      title: '闻铎：签在证人栏上的名字',
      text: '茶室已经关了。他带你走进四十九层尽头的档案间，制冷机的低鸣一直没停。J-1147 的最后一份文件摊在桌上，证人栏空着，笔已经旋开。他说：「签下去，我就是你的把柄；不签，你就成了我的。」说这句话时他手里还握着下午那只凉茶杯，杯壁的水痕干了一半。',
      when: { minFolded: 9 },
      options: [
        { label: '签字，站在他这一边', relation: 3, run: { intel: 4, track: { power: 2, sin: 1 } }, flag: 'wd_witness' },
        { label: '不签，把文件交回监事会', relation: -2, run: { track: { loyalty: 3, power: 1 } }, flag: 'wd_reported' },
        { label: '签，把复印件留给灰市', relation: 0, run: { money: 60, track: { sin: 2, renown: -1 } }, flag: 'wd_leak' },
      ],
    },

    /* ============ 苏纹 · 董事会日程官 · 高塔商业区 ============ */
    {
      id: 'sw-1',
      npc: 'su-wen',
      stage: 1,
      act: 1,
      district: 'tower',
      title: '苏纹：这一格本来不是你的',
      text: '周三下午三点，苏纹把周会往后挪了二十分钟，空出一格给你。她说这个时间不是她挑的，是有人替你留的。她低头在排期表上划了一道，用的是铅笔，划得很轻，像随时准备擦掉。走廊尽头的电梯停了一下层，她立刻把表合上，问你今天来高塔到底是为了什么。',
      when: { minFolded: 1 },
      options: [
        { label: '问她是谁替我留的时间', relation: 2, run: { intel: 3 }, flag: 'sw_asked' },
        { label: '道谢，什么都不多问', relation: 1, run: { track: { loyalty: 1 } } },
        { label: '说这个时间我不会来', relation: -1, run: { track: { power: 1 } } },
      ],
    },
    {
      id: 'sw-2',
      npc: 'su-wen',
      stage: 2,
      act: 2,
      district: 'tower',
      title: '苏纹：她第一次改了别人的表',
      text: '她把你的面谈挪到今晚十一点，理由写得规整：对方时间调整。排期表推到你面前，那一格里原本排着另一个人，名字被她用橡皮擦得很干净，只剩一点灰。她说这是她第一次替别人改表，现在退回去还来得及，只是退回去以后，那一格里填的就不会是你了。',
      when: { minFolded: 5 },
      options: [
        { label: '去，并让她留一份记录', relation: 3, run: { intel: 2, track: { loyalty: 1, power: 1 } }, flag: 'sw_kept_slot' },
        { label: '让她把表改回原样', relation: -1, run: { track: { loyalty: 1, power: -1 } } },
        { label: '问那个被擦掉的人是谁', relation: 2, run: { intel: 4, track: { sin: 1 } } },
      ],
    },
    {
      id: 'sw-3',
      npc: 'su-wen',
      stage: 3,
      act: 3,
      district: 'tower',
      title: '苏纹：最后一格空白',
      text: '她约你在四十七层的空会议室见面，没有开灯，只有屏幕的光。桌上摊着这半个月的排期表，三个时段是空的，空得不像她排出来的。她说这三个空档是她给自己留的，也是给你留的。她把铅笔折成两截放在桌上，说这一次她不动笔，你想填什么就填什么。',
      when: { minFolded: 9 },
      options: [
        { label: '把空档填上她的名字', relation: 3, run: { intel: 3, track: { loyalty: 1, power: 2 } }, flag: 'sw_saved_her' },
        { label: '交回董事会，写明三个空档', relation: -2, run: { track: { loyalty: 3, renown: -1 } }, flag: 'sw_handed' },
        { label: '什么都不填，把表撕了', relation: 1, run: { track: { sin: 1, renown: 1 } } },
      ],
    },

    /* ============ 郁南枝 · 清算行首席 · 交易所广场 ============ */
    {
      id: 'yn-1',
      npc: 'yu-nanzhi',
      stage: 1,
      act: 1,
      district: 'exchange',
      title: '郁南枝：三十七万的尾差',
      text: '交易所广场的清算行到晚上八点还亮着灯，屏幕上的数字一列列往下滚。郁南枝把昨天的清算单推过来，尾差三十七万，来源栏填的是你的部门编号。她递给你一支铅笔，让你自己圈出那一行。她说她只问数字不问人，今天这行数字上偏偏写着你的名字，你要她怎么抬头。',
      when: { minFolded: 1 },
      options: [
        { label: '圈出来，照着实话说明', relation: 2, run: { track: { loyalty: 2 } }, flag: 'yn_honest' },
        { label: '问她这行到底是谁填的', relation: 1, run: { intel: 3, track: { loyalty: -1 } } },
        { label: '说这不是我的部门编号', relation: -2, run: { track: { sin: 1 } } },
      ],
    },
    {
      id: 'yn-2',
      npc: 'yu-nanzhi',
      stage: 2,
      act: 2,
      district: 'exchange',
      title: '郁南枝：一笔挂了三年多的坏账',
      text: '她调出一笔挂了三年多的坏账，打印机一张一张往外吐纸。账上的人早就不在了，只剩一个还在世的联系人每年寄一次函。她要你把这笔账连同那个联系人的追索权一起终结。她的手指按在纸面那行姓氏上停了很久，那正是她自己的姓，她没说，你也没有问。',
      when: { minFolded: 5 },
      options: [
        { label: '帮她核销，先问清缘由', relation: 2, run: { money: 55, intel: 2, track: { sin: 1 } } },
        { label: '按流程把坏账上报', relation: -2, run: { track: { loyalty: 2, renown: 1 } } },
        { label: '要她先说清和这人的关系', relation: 1, run: { intel: 4, track: { sin: 1 } } },
      ],
    },
    {
      id: 'yn-3',
      npc: 'yu-nanzhi',
      stage: 3,
      act: 3,
      district: 'exchange',
      title: '郁南枝：签收栏上的第二个名字',
      text: '凌晨的清算室里只剩一台终端在响。她把一份调整单放在你面前，金额栏写着一个刚好能把整条线抹平的数字，签收人栏留了两个空位。她说第一个她签，第二个留给你。铅笔递过来时笔尖已经削好，纸边压着一枚回形针，回形针上还夹着白天那张清算单的一角。',
      when: { minFolded: 9 },
      options: [
        { label: '签第二个名字，替她平账', relation: 3, run: { money: 70, track: { sin: 2, power: 1 } }, flag: 'yn_covered' },
        { label: '不签，把调整单交给监事会', relation: -2, run: { track: { loyalty: 3, power: -1 } }, flag: 'yn_reported' },
        { label: '签，但把原件复印一份', relation: 1, run: { intel: 4, track: { sin: 1, renown: -1 } }, flag: 'yn_copy' },
      ],
    },

    /* ============ 戴思远 · 合规伦理审查官 · 交易所广场 ============ */
    {
      id: 'ds-1',
      npc: 'dai-siyuan',
      stage: 1,
      act: 1,
      district: 'exchange',
      title: '戴思远：第三页的红笔圈',
      text: '合规处的会议室没有窗，只有一盏顶灯，灯管偶尔响一声。戴思远把审计底稿推给你，第三页用红笔圈住了差旅与耗材两项，旁边写着三成。他说这一刀必须你签，留下来的那部分算你替他们争的。他把笔递过来，手腕上那圈旧表带磨得快断，露出的压痕很深。',
      when: { minFolded: 1 },
      options: [
        { label: '签，并问这一刀砍到谁', relation: 2, run: { money: 25, intel: 2, track: { loyalty: 1 } } },
        { label: '要求先看完整本底稿', relation: 1, run: { intel: 3, track: { loyalty: -1 } } },
        { label: '直接拒签，退回底稿', relation: -2, run: { track: { renown: 2, loyalty: -1 } } },
      ],
    },
    {
      id: 'ds-2',
      npc: 'dai-siyuan',
      stage: 2,
      act: 2,
      district: 'exchange',
      title: '戴思远：一份他签过的例外',
      text: '他把你叫进问询室，桌上摊着他三年前签过的一份合规例外，编号是红笔写的，纸角已经卷起。他说这份例外如今成了事故链条上的一环，签字的人只有他一个。他问你那份授权书副本还在不在你手里，问得很慢，眼睛一直没抬，手指在编号上蹭了两下。',
      when: { minFolded: 5 },
      options: [
        { label: '把副本给他，替他兜住', relation: 3, run: { intel: 2, track: { sin: 1 } } },
        { label: '告诉他副本早就不在了', relation: -1, run: { track: { loyalty: 1 } } },
        { label: '问他要拿什么换这份副本', relation: 0, run: { money: 50, track: { sin: 1, power: 1 } } },
      ],
    },
    {
      id: 'ds-3',
      npc: 'dai-siyuan',
      stage: 3,
      act: 3,
      district: 'exchange',
      title: '戴思远：他第一次没有签自己',
      text: '合规处的灯只开了一半，另一半坏了很久没人报修。他把一份新的例外申请推到桌子中间，申请人一栏写着另一个部门，签批人栏空着。他说这一份理由不成立，他不能签，也不想让你签。他把笔帽慢慢拧上，说这是他第一次不合规，剩下的事他一个人扛。',
      when: { minFolded: 9 },
      options: [
        { label: '把申请撤掉，替他担半份', relation: 3, run: { track: { renown: 2, loyalty: -1, power: 1 } }, flag: 'ds_covered' },
        { label: '照流程签掉，这才合规', relation: -2, run: { track: { loyalty: 3, sin: 1 } }, flag: 'ds_signed' },
        { label: '把申请和例外清单寄出去', relation: 0, run: { track: { renown: -2, sin: 1, power: 1 } }, flag: 'ds_leak' },
      ],
    },

    /* ============ 程砚 · 首席科学家 · 研究所园区 ============ */
    {
      id: 'cy-1',
      npc: 'cheng-yan',
      stage: 1,
      act: 1,
      district: 'lab',
      title: '程砚：三号柜少了十一支',
      text: '研究所园区的走廊很干净，冷得像医院。程砚带你走到三号柜前，样本登记表停在上周三，中间少了十一支。她不要你解释去向，只要求本周内把表补齐，扫码栏空着，签字栏也空着。说完她就去看培养箱，背对着你站了很久，玻璃里映出的数字一直在往上跳。',
      when: { minFolded: 1 },
      options: [
        { label: '补齐表格，扫码栏留空', relation: 2, run: { intel: 2, gear: 1 } },
        { label: '追问这十一支去了哪', relation: 1, run: { intel: 3, track: { sin: 1 } } },
        { label: '不接这张表，让她找别人', relation: -2, run: { track: { loyalty: 1, power: -1 } } },
      ],
    },
    {
      id: 'cy-2',
      npc: 'cheng-yan',
      stage: 2,
      act: 2,
      district: 'lab',
      title: '程砚：名册上多出来的那一行',
      text: '她把一份志愿者名册摊在实验台上。三号志愿者昨天出所之后再没有回来，签名还留在名册上，体检数据也还挂在系统里。她说需要这个名字在今天之内从名册上消失，数据她自己处理。旁边那台培养箱一直在响，像有什么东西在敲玻璃，她说话时手一直按着台面。',
      when: { minFolded: 5 },
      options: [
        { label: '替她把这一行抹掉', relation: 2, run: { gear: 1, track: { sin: 2, power: 1 } } },
        { label: '不抹，先查这人去了哪', relation: 0, run: { intel: 4, track: { renown: 1, sin: -1 } } },
        { label: '把名册原样交回伦理组', relation: -2, run: { track: { loyalty: 2, renown: 1 } } },
      ],
    },
    {
      id: 'cy-3',
      npc: 'cheng-yan',
      stage: 3,
      act: 3,
      district: 'lab',
      title: '程砚：签收栏',
      text: '三号实验室的灯全开着，一只没有标号的金属箱放在台面上，冷链记录停在前天凌晨。程砚把一份签收单推到你面前，签收人栏只留了一行空位。她说没人敢签，包括她自己。她站在箱子旁边，手从头到尾都搭在台面上，既没有碰过那只箱子，也没有看你。',
      when: { minFolded: 9 },
      options: [
        { label: '签字接收，站到她这边', relation: 3, run: { gear: 1, intel: 3, track: { sin: 1, power: 2 } }, flag: 'cy_signed' },
        { label: '不签，把签收单上报董事会', relation: -2, run: { track: { loyalty: 3, renown: 1 } }, flag: 'cy_reported' },
        { label: '签，但先把数据拷一份', relation: 0, run: { intel: 4, track: { sin: 2 } }, flag: 'cy_backup' },
      ],
    },

    /* ============ 彭戬 · 研究所安保总管 · 研究所园区 ============ */
    {
      id: 'pj-1',
      npc: 'peng-jian',
      stage: 1,
      act: 1,
      district: 'lab',
      title: '彭戬：缺了签名的那一趟',
      text: '安保总控室里有四块屏，最左边那块一直闪着红点。彭戬把一叠巡检单拍在你桌上，说周二凌晨那趟无人值守缺了签名。他知道不是你值的班，可系统里挂的是你的编号。他把笔递过来，说补签只要两分钟，笔就在他手里，签完这叠单子当场就归档。',
      when: { minFolded: 1 },
      options: [
        { label: '补签，先把事情压下去', relation: 2, run: { track: { power: 1, sin: 1 } } },
        { label: '问他是谁动了系统', relation: 1, run: { intel: 3, track: { loyalty: -1 } } },
        { label: '不在任何单子上签字', relation: -2, run: { track: { loyalty: 2, power: -1 } } },
      ],
    },
    {
      id: 'pj-2',
      npc: 'peng-jian',
      stage: 2,
      act: 2,
      district: 'lab',
      title: '彭戬：钥匙盘上少了一把',
      text: '他把安保台的钥匙盘转到你面前，第三格是空的。他说昨晚有一批设备从三号走廊运出去，报的是你的工号，记录会跟着设备一起出园区，出到哪一步都算不到你头上。他问你还要不要那份临时授权，问到一半停住了，因为走廊的灯恰好灭了一排，四块屏上有两块跟着暗下去。',
      when: { minFolded: 5 },
      options: [
        { label: '给授权，帮他把记录抹掉', relation: 2, run: { gear: 1, track: { sin: 2 } } },
        { label: '不授权，让他向上面解释', relation: -1, run: { track: { loyalty: 2, renown: 1 } } },
        { label: '授权，要他记下谁下指令', relation: 1, run: { intel: 4, track: { sin: 1, power: 1 } } },
      ],
    },
    {
      id: 'pj-3',
      npc: 'peng-jian',
      stage: 3,
      act: 3,
      district: 'lab',
      title: '彭戬：他第一次没有开门',
      text: '凌晨三点，安保总控室只剩他一个人，四块屏有两块黑着。门禁读卡器一直在响，第七道上锁申请挂在屏上不动，卡号属于一个不该出现在园区里的人。他说他已经按过三次确认，这一次按了取消。他把钥匙盘推到桌子中间，说这道门他不开，明天写报告也好，撤职也好，他都认。读卡器又响了一声，屏幕上的时间跳到三点零七分。',
      when: { minFolded: 9 },
      options: [
        { label: '站他这边，这道门不开', relation: 3, run: { track: { renown: 2, loyalty: -1, power: 1 } }, flag: 'pj_refused' },
        { label: '替他开门，记录算我头上', relation: 1, run: { intel: 2, track: { sin: 2, loyalty: 1 } } },
        { label: '按确认，上报他拒令', relation: -2, run: { track: { loyalty: 3, renown: -1 } }, flag: 'pj_reported' },
      ],
    },

    /* ============ 老鸦 · 灰市掮客 · 下层居住区 ============ */
    {
      id: 'ly-1',
      npc: 'lao-ya',
      stage: 1,
      act: 1,
      district: 'slum',
      title: '老鸦：水泵房里的第一笔账',
      text: '下层旧水泵房的水声一晚上没停，铁管上结着一层白霜。老鸦蹲在管道边上，手边摊着一本手写账本，字歪得能看出是用左手写的。他说上次那件事他记住了，记住的方式是在账本上给你留了一行。他把账本合上，说这一行你先别问价，位置留着就行。',
      when: { minFolded: 1 },
      options: [
        { label: '认下这一行，问他图什么', relation: 2, run: { money: 20, intel: 2, track: { sin: 1 } } },
        { label: '把账本还他，这行不认', relation: -1, run: { track: { loyalty: 1, renown: 1 } } },
        { label: '问他这一行值多少', relation: 0, run: { money: 35, track: { sin: 1 } } },
      ],
    },
    {
      id: 'ly-2',
      npc: 'lao-ya',
      stage: 2,
      act: 2,
      district: 'slum',
      title: '老鸦：名单上的一个旧交情',
      text: '他把你约到水管边的铁梯上，说下层的清理名单里有个人不该在上面。这人和他有点旧交情，早年替他挡过一刀，刀口到现在还留着。他不要你做什么大事，只要名单走流程的时候你多按一次暂停。他从口袋掏出一包没拆的烟，看了看又塞了回去，说这包是他留到事情办成那天才拆的。铁梯下面的水声一阵一阵的，他问你上次那件事，是不是还记着。',
      when: { minFolded: 5 },
      options: [
        { label: '按暂停，帮他把人留下', relation: 3, run: { track: { renown: 2, sin: 1, loyalty: -1 } }, flag: 'ly_saved' },
        { label: '不管这事，名单照走', relation: -2, run: { track: { loyalty: 1, sin: 1 } }, flag: 'ly_dropped' },
        { label: '按暂停，让他欠我一条', relation: 1, run: { intel: 3, track: { power: 1, sin: 1 } } },
      ],
    },
    {
      id: 'ly-3',
      npc: 'lao-ya',
      stage: 3,
      act: 3,
      district: 'slum',
      title: '老鸦：他撕了账本的第一页',
      text: '水泵房今晚没开灯，只有铁桶上那本账本翻着。老鸦翻到第一页，那一页记着灰市三十年的规矩：谁的货、谁的名字、谁的价，一条不漏。他说规矩里有一条，掮客不能替客户顶罪。现在他要撕掉这一页，手指已经按在纸边上，只等你点一下头。他说撕了以后灰市再没有他的位置，也再没有他替你挡下的那条规矩。铁桶上那本账本翻着，一页都还没少。',
      when: { minFolded: 9 },
      options: [
        { label: '让他撕，这份情我认下', relation: 3, run: { intel: 3, track: { renown: 1, sin: -1, power: 1 } }, flag: 'ly_tore' },
        { label: '把账本夺回来，规矩不能破', relation: -2, run: { track: { loyalty: 2, power: 1 } }, flag: 'ly_kept' },
        { label: '让他撕，但先抄一份页', relation: 1, run: { intel: 4, track: { sin: 1, renown: -1 } }, flag: 'ly_copied' },
      ],
    },

    /* ============ 陆晚 · 无证诊所医生 · 下层居住区 ============ */
    {
      id: 'lw-1',
      npc: 'lu-wan',
      stage: 1,
      act: 1,
      district: 'slum',
      title: '陆晚：手写单上的第七行',
      text: '无证诊所开在半层地下，消毒水味盖不住铁锈味。陆晚一边给你手上的划口穿线，一边说下个月那批药到了就得换新的。她把一张手写单推给你，第七行写着你的名字，剂量和时间都标好了，字是她的，笔画很急。她没抬头，说这一行她记了三个月。',
      when: { minFolded: 1 },
      options: [
        { label: '按单子来，把药钱付掉', relation: 2, run: { money: 45, track: { renown: 2, sin: -1 } } },
        { label: '问她为什么单记我一行', relation: 1, run: { intel: 3, track: { renown: 1 } } },
        { label: '拿走单子，药我自己弄', relation: -2, run: { track: { loyalty: 1, sin: 1 } } },
      ],
    },
    {
      id: 'lw-2',
      npc: 'lu-wan',
      stage: 2,
      act: 2,
      district: 'slum',
      title: '陆晚：一只没有编号的旧义体',
      text: '她从柜子底层翻出一只旧义体，外壳磨得发白，接口处没有编号。她说这是给一个人留的，那人现在过不了闸机，也付不起钱。她要一份能过闸机的身份记录，只要一份，三天之内都算数。诊室外面有人一直在咳嗽，从头到尾没有停过，她说话时朝门口看了一眼。',
      when: { minFolded: 5 },
      options: [
        { label: '帮她弄一份身份记录', relation: 3, run: { money: 35, track: { renown: 2, sin: 1, loyalty: -1 } }, flag: 'lw_made_id' },
        { label: '帮不了，这事风险太大', relation: -2, run: { track: { loyalty: 1, sin: -1 } } },
        { label: '先见这个人，再决定', relation: 1, run: { intel: 3, track: { renown: 1 } } },
      ],
    },
    {
      id: 'lw-3',
      npc: 'lu-wan',
      stage: 3,
      act: 3,
      district: 'slum',
      title: '陆晚：她第一次选了边',
      text: '诊所里多了两张床，靠里那张躺着一个穿灰制服的人。陆晚把一瓶标着别人名字的血浆塞进柜子，说你身后那条巷子里还有四个在等，她只来得及救一个。她把那张手写单撕成两半，一半塞进你手里，问你愿不愿意替她决定这一次该救谁。她从来不选边，缝过所有阵营的人，这一次她说她选不出来，选得出来的只有你。',
      when: { minFolded: 9 },
      options: [
        { label: '救制服那人，先问他是谁', relation: 0, run: { intel: 3, track: { loyalty: 2, renown: 1 } }, flag: 'lw_side_system' },
        { label: '救巷子那边，听她的', relation: 3, run: { track: { renown: 2, loyalty: -1, sin: 1 } }, flag: 'lw_side_out' },
        { label: '两边都不救，把人推走', relation: -2, run: { track: { renown: -1, sin: 1 } }, flag: 'lw_neutral' },
      ],
    },

  ];
})();
