/* NPC 个人支线 B 组。每人三幕：相识 / 交情 / 分晓。 */
(function () {
  'use strict';

  window.STORY_NPC_B = [
    /* ---------------- 铁贵 · 装卸工会头目 · docks ---------------- */
    {
      id: 'tg-1',
      npc: 'tie-gui',
      stage: 1,
      act: 1,
      district: 'docks',
      title: '铁贵：吊机下面那句话',
      text: '雨从穹顶接缝漏下来，在吊机底下积成一洼。铁贵站在那洼水里，雨衣湿透了也没脱，手里攥着一张装卸计件单。罢工第二天，三台吊机全停，警报灯从早亮到现在。他不是来找你讲道理，是把单子递过来：「上面这批货的报备号是你部门批的。你只要说一句，这是你自己签的。」',
      when: { minFolded: 1 },
      options: [
        { label: '当着工人的面替他说', relation: 2, run: { intel: 2, track: { renown: 1 } }, flag: 'tg_stood_up' },
        { label: '把单子收下，什么也不说', relation: 1, run: { intel: 2, track: { sin: 1 } } },
        { label: '说这不是你签的，转身走', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'tg-2',
      npc: 'tie-gui',
      stage: 2,
      act: 2,
      district: 'docks',
      title: '铁贵：第四天的手',
      text: '罢工进入第四天。冷库的制冷机一直在低鸣，货箱表面结了一层白霜。铁贵左手新换了绷带，边缘渗出一点黄。他把你叫到卷帘门后面，声音压得很低：「昨天夜里带走两个人，工号都记在我这儿。上面说停工时按天扣，扣满就把名额交给巡检。我要撑，就得让三十个人替我扛。」',
      when: { minFolded: 5 },
      options: [
        { label: '替他把两个工号藏进旧档案', relation: 3, run: { intel: 3, track: { sin: 2, renown: 1 } }, flag: 'tg_hid_roster' },
        { label: '劝他先把夜班撤下来', relation: 1, run: { intel: 2, track: { loyalty: 1 } } },
        { label: '说这局你插不了手', relation: -2, run: { track: { loyalty: 2 } } },
      ],
    },
    {
      id: 'tg-3',
      npc: 'tie-gui',
      stage: 3,
      act: 3,
      district: 'docks',
      title: '铁贵：把灯拆下来',
      text: '工会礼堂里，吊机上那盏警报灯被人拆了下来，摆在讲台正中，玻璃罩裂了一道。铁贵站在灯后面，四天拖成了十一天，工人少了七个。他念完名单，抬起头看你：「我准备签字复工，条件我一个人扛，名字不写别人的。你要想拦现在说；你要想接这份名单，也现在说。」',
      when: { minFolded: 9 },
      options: [
        { label: '站他这边，把名字接过来', relation: 3, run: { intel: 3, track: { renown: 2, sin: 1 } }, flag: 'tg_signed_with_him' },
        { label: '把名单交给董事会换复工', relation: -2, run: { money: 60, track: { loyalty: 2 } }, flag: 'tg_sold_out' },
        { label: '不拦他，也不接名单', relation: -1, run: { intel: 1, track: { sin: -1 } } },
      ],
    },

    /* ---------------- 银面 · 女术士的代理人 · docks ---------------- */
    {
      id: 'ym-1',
      npc: 'yin-mian',
      stage: 1,
      act: 1,
      district: 'docks',
      title: '银面：多出来的一次停电',
      text: '旧售票亭的玻璃上贴着停用七年的牌子。银面坐在里面，桌上一杯茶已经凉了，没动过。她没抬头：「码头明早六点四十会停一次电，十七分钟。停电那会儿，你的手机会收到一条不存在的到港通知。」你看了眼表，现在是六点三十八。她说完这句，才抬手示意你坐下。',
      when: { minFolded: 1 },
      options: [
        { label: '坐下，问她凭什么知道', relation: 2, run: { intel: 3 }, flag: 'ym_sat_down' },
        { label: '记下时间，先离开这里', relation: 0, run: { intel: 2, chips: 1 } },
        { label: '说这种把戏没人信', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'ym-2',
      npc: 'yin-mian',
      stage: 2,
      act: 2,
      district: 'docks',
      title: '银面：她说的我们',
      text: '她约在停用货梯的机房，制冷机的低鸣比上次更响。门是从外面反锁的，锁舌上有新的刮痕。她从风衣内袋里抽出一张手写单，边角已经被攥软：「上周三下午三点十一分，有人拿这张单来提货。签名栏是我的字，但那不是我写的。」她说她的委托人已经在问这张单的下落，问到第二次就开始问她什么时候方便办离职。她把单子递到一半又收回去，「你拿着它，就等于替我把这件事认下来。」',
      when: { minFolded: 5, minRel: 2 },
      options: [
        { label: '接过单子，替她扛住这件事', relation: 3, run: { intel: 3, track: { sin: 2, power: 1 } }, flag: 'ym_took_slip' },
        { label: '不接，但帮她把签名比对清楚', relation: 1, run: { intel: 4, track: { sin: 1 } } },
        { label: '让她自己交上去，你只当没见过', relation: -2, run: { track: { loyalty: 2, renown: -1 } } },
      ],
    },
    {
      id: 'ym-3',
      npc: 'yin-mian',
      stage: 3,
      act: 3,
      district: 'docks',
      title: '银面：替她说出那句话',
      text: '还是那间售票亭，停用的牌子掉了，凉茶的杯底在桌上留下一个圈。银面把一张写满缩写的手写单推过来，纸边上的字迹不像同一支笔写的。「这些编号里有一个是我的，可这些编号不是我的。」她第一次用「你的人」这个词，话却停在半句上，「你替我把那句话带出去，我就算你这边的人。」',
      when: { minFolded: 9 },
      options: [
        { label: '把话替她带出去，认下她', relation: 3, run: { intel: 3, track: { renown: 1, sin: 1 } }, flag: 'ym_spoke_for_her' },
        { label: '把单子交上去，摘清自己', relation: -2, run: { money: 50, track: { loyalty: 2 } }, flag: 'ym_reported' },
        { label: '把单子推回去，不接', relation: -1, run: { intel: 1, track: { sin: -1 } } },
      ],
    },

    /* ---------------- 温仕成 · 引航票务掮客 · orbit ---------------- */
    {
      id: 'ws-1',
      npc: 'wen-shicheng',
      stage: 1,
      act: 1,
      district: 'orbit',
      title: '温仕成：一张不该有的票',
      text: '轨道港的候船厅里，广播每九十秒报一次登船号。温仕成把一张纸质票夹在指缝间，票面上印的出发日期是后天，可舱位号在今天的系统里已经存在。「这张票不该有。」他说，「但它已经过了闸机。我只想知道，是你们部门放的行，还是有人借了你的编制号。」',
      when: { minFolded: 1 },
      options: [
        { label: '把票收下，去查闸机记录', relation: 2, run: { intel: 3 }, flag: 'ws_took_ticket' },
        { label: '让他自己走流程报备', relation: 0, run: { track: { loyalty: 1 } } },
        { label: '说这票跟我部门无关', relation: -1, run: { intel: 1 } },
      ],
    },
    {
      id: 'ws-2',
      npc: 'wen-shicheng',
      stage: 2,
      act: 2,
      district: 'orbit',
      title: '温仕成：名单在变长',
      text: '引航层的走廊结着一层薄冰，管道外壁挂了霜。温仕成蹲在消防柜前，借着工作灯抄一份名单，纸上有十七个名字，其中四个被划掉又写回。「改名单的人用的是你们部门的模板。」他把灯递给你，「三个月前九个，现在十七个。我不查底细，我只想活到下个月还能卖票。」',
      when: { minFolded: 5, minRel: 2 },
      options: [
        { label: '替他做一份备份名单', relation: 2, run: { intel: 3, chips: 1 }, flag: 'ws_backup' },
        { label: '劝他停手，先离港', relation: 1, run: { money: -40, track: { renown: 1 } } },
        { label: '把名单收走，按流程上交', relation: -2, run: { money: 45, track: { loyalty: 2, sin: 1 } } },
      ],
    },
    {
      id: 'ws-3',
      npc: 'wen-shicheng',
      stage: 3,
      act: 3,
      district: 'orbit',
      title: '温仕成：第十八行',
      text: '他在登船口截住你，手里还是那份手写名单，第十七行下面多出一行新的，墨迹还没干。写的是他自己的名字，舱位号空着，改动用的还是你们部门的模板。「今天早上进的系统。」他把纸撕成两半，一半塞给你，「票我不卖了，人我得走。你拿这半张，够不够换我上那班船。」',
      when: { minFolded: 9 },
      options: [
        { label: '用半张单换他上船', relation: 3, run: { intel: 4, track: { renown: 1, sin: 1 } }, flag: 'ws_sent_him_off' },
        { label: '把两半纸都交上去', relation: -2, run: { money: 55, track: { loyalty: 3 } }, flag: 'ws_handed_list' },
        { label: '不接单，让他自己走', relation: -1, run: { track: { sin: -1 } } },
      ],
    },

    /* ---------------- 雨客 · 潮的接触人 · orbit ---------------- */
    {
      id: 'yk-1',
      npc: 'yu-ke',
      stage: 1,
      act: 1,
      district: 'orbit',
      title: '雨客：他来传的那句话',
      text: '轨道港的货运通道湿度常年七十往上，墙上挂着一层水珠，鞋底每一步都带响。雨客站在闸口外侧，穿着一件拧不干的雨衣，把一个密封袋按在胸口。他不是来递东西的，是来念话的：「潮说，穹顶第七接缝在响，已经响过三次。第三次，你能听见。」念完他没有立刻走，手指在袋子封口上按了两下，像在等一句别的话。你问他袋子里是什么，他说不归他管，他只负责把话带到，带完就空着手回去。',
      when: { minFolded: 2 },
      options: [
        { label: '先问他这一趟跑了多久', relation: 2, run: { intel: 2, track: { renown: 1 } }, flag: 'yk_asked_him' },
        { label: '让他把密封袋交给你', relation: 0, run: { intel: 3, track: { sin: 1 } } },
        { label: '说接缝的事不该你管', relation: -2, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'yk-2',
      npc: 'yu-ke',
      stage: 2,
      act: 2,
      district: 'orbit',
      title: '雨客：他第一次说我要',
      text: '他在换乘站的长椅上等了两个多小时，雨衣没换，水在座位底下积成一小片。他先说完该传的话，说潮要你三天内回话，然后停了很久，才补上一句不属于传话的句子：「我有个妹妹在环带，工号被划进回收名单了。这句不是潮要我说的，是我自己要说。」',
      when: { minFolded: 5 },
      options: [
        { label: '答应替他查那个工号', relation: 3, run: { intel: 3, track: { sin: 1, renown: 1 } }, flag: 'yk_promised' },
        { label: '说清你能帮的和不能帮的', relation: 1, run: { intel: 2 } },
        { label: '回绝，让他只传话就好', relation: -2, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'yk-3',
      npc: 'yu-ke',
      stage: 3,
      act: 3,
      district: 'orbit',
      title: '雨客：雨衣里面的东西',
      text: '他把你叫到第七接缝外侧，风从缝里穿过来，那件雨衣被吹得鼓起来。他把密封袋打开了，里面是妹妹的工牌和一张手写条，都不是潮的东西。「潮让我骗你一次，我没做。」他说，「这两样留给你，上不上报随你。你不报，我明天就得消失；你报了，我就回不去了。」',
      when: { minFolded: 9 },
      options: [
        { label: '收下工牌，替他压住', relation: 3, run: { intel: 3, track: { sin: 2 } }, flag: 'yk_kept_him' },
        { label: '上报，换他一条活路', relation: -1, run: { money: 50, track: { loyalty: 2, renown: -1 } }, flag: 'yk_reported_him' },
        { label: '两样都不收，让他自己选', relation: 0, run: { intel: 1 } },
      ],
    },

    /* ---------------- 荀戒 · 环带巡检员 · ring ---------------- */
    {
      id: 'xj-1',
      npc: 'xun-jie',
      stage: 1,
      act: 1,
      district: 'ring',
      title: '荀戒：照着手册念',
      text: '环带维修层的长廊结着冰，走一步要踢一下脚尖的霜。荀戒举着手电逐格照焊缝，照完一格念一句：「第七段，编号 0417，无位移，无渗漏，结论合格。」念到中途他停住，把手电压低：「按规程，你不该在这一层。你可以解释，也可以现在离开，我不记。」',
      when: { minFolded: 1 },
      options: [
        { label: '解释自己是来查编号的', relation: 2, run: { intel: 3 }, flag: 'xj_explained' },
        { label: '递上证件，请他照章记录', relation: 1, run: { track: { loyalty: 1 } } },
        { label: '不说话，转身离开', relation: 0, run: { intel: 1 } },
      ],
    },
    {
      id: 'xj-2',
      npc: 'xun-jie',
      stage: 2,
      act: 2,
      district: 'ring',
      title: '荀戒：对不上的那一格',
      text: '他把手电照在第三十一格焊缝上，那里有一道新痕，编号被磨掉了一半。「按本子，这一格三个月前就封过了。」他翻回上一页，又翻回来，来回翻了三遍，最后把手电关了，「照规程我该报异常。异常上报要停整段环带，停一天，下面三千人的水就断一天。你说我记哪一页。」',
      when: { minFolded: 5 },
      options: [
        { label: '让他按规程报，别自己扛', relation: 0, run: { track: { loyalty: 2, renown: -1 } } },
        { label: '让他先瞒，你去查那道痕', relation: 2, run: { intel: 4, track: { sin: 1 } }, flag: 'xj_covered' },
        { label: '说这不是你该管的', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'xj-3',
      npc: 'xun-jie',
      stage: 3,
      act: 3,
      district: 'ring',
      title: '荀戒：他改了那一页',
      text: '巡检本摊在操作台上，第三十一格那一页被重新写过，墨色和前后页都不一样。荀戒站在旁边，手电没开。「我改了。」他说得很平，「他们查下来，是我一个人的事。你只要做一件事：告诉我那道痕是人磨的，还是冻裂的。你说哪样，我就认哪样，我不再问你第二遍。」',
      when: { minFolded: 9 },
      options: [
        { label: '替他把这道痕说成冻裂', relation: 3, run: { intel: 3, track: { sin: 2 } }, flag: 'xj_lied_for_him' },
        { label: '如实说，是有人磨的', relation: -1, run: { intel: 4, track: { loyalty: 2, renown: -1 } }, flag: 'xj_told_truth' },
        { label: '不答，让他自己去验', relation: 0, run: { intel: 2 } },
      ],
    },

    /* ---------------- 萨尔 · 潮的拾荒者 · outside ---------------- */
    {
      id: 'se-1',
      npc: 'sa-er',
      stage: 1,
      act: 1,
      district: 'outside',
      title: '萨尔：穹顶外面的人',
      text: '穹顶外壳的水顺着缝隙往下滴，滴在一块拆到一半的义体上，把编号冲得看不清了。萨尔蹲在旁边，用一把断头螺丝刀刮线路板。你走近，她先把手里的东西塞进怀里，然后才看你：「里面的。四个人来过，三个要买我的件，一个要烧我的窝。」她伸出手：「你哪个。」',
      when: { minFolded: 2 },
      options: [
        { label: '蹲下，帮她拆那块板', relation: 2, run: { intel: 2, gear: 1 }, flag: 'se_helped' },
        { label: '说明你来问接缝的事', relation: 1, run: { intel: 3 } },
        { label: '什么都不说，退回去', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'se-2',
      npc: 'sa-er',
      stage: 2,
      act: 2,
      district: 'outside',
      title: '萨尔：她把泵让给你',
      text: '她的窝被撬了，义体零件散了一地，编号牌全不见了。萨尔坐在门口，小腿肿着，没让人扶。她把一支还能用的滤水泵推到你脚边：「潮里泡过的东西，喝了不干净。」她说得很短，像每个字都要省着用，「你拿这个。换你帮我查一件事，谁把编号牌收走的。」',
      when: { minFolded: 5 },
      options: [
        { label: '接下泵，答应替她查', relation: 3, run: { gear: 1, intel: 2, track: { sin: 1 } }, flag: 'se_deal' },
        { label: '不收泵，只答应查编号牌', relation: 2, run: { intel: 3, track: { renown: 1 } } },
        { label: '说外面的事你插不了手', relation: -2, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'se-3',
      npc: 'sa-er',
      stage: 3,
      act: 3,
      district: 'outside',
      title: '萨尔：她第一次让你往里走',
      text: '她带你到穹顶正下方一间没有窗的屋子，地上摆着十几块编号牌，都是从义体上拆下来的。她把滤水泵放回你手里，泵壳上多了几道新划痕。「这块是你部门发出去的。」她指着一块牌子，「你现在有两条路：带走它去交差，或者把它留下，帮我记这十几个人原来叫什么。」',
      when: { minFolded: 9 },
      options: [
        { label: '留下，帮她记下名字', relation: 3, run: { intel: 3, track: { renown: 2, sin: 1 } }, flag: 'se_stayed' },
        { label: '带牌子走，按流程上报', relation: -2, run: { money: 55, track: { loyalty: 2 } }, flag: 'se_took_plate' },
        { label: '把泵还她，谁也不欠谁', relation: -1, run: { track: { sin: -1 } } },
      ],
    },

    /* ---------------- 班头 · 回收场领班 · salvage ---------------- */
    {
      id: 'bt-1',
      npc: 'ban-tou',
      stage: 1,
      act: 1,
      district: 'salvage',
      title: '班头：传送带上的那条手臂',
      text: '回收场的传送带一直响，制冷机把仓房压到零下。班头戴着一副磨白的皮手套，从带子上拎起一条拆到一半的义体手臂，翻过来看编号，又放回去。「这个月第三十二条。」他冲你抬了抬下巴，「你们部门的单子写的是拆干净，可这条手臂的接管还是热的。你说我照单办，还是照人办。」',
      when: { minFolded: 1 },
      options: [
        { label: '让他照人办，先别拆', relation: 2, run: { intel: 2, track: { sin: 1 } }, flag: 'bt_kept_arm' },
        { label: '照单办，把编号登记清楚', relation: 1, run: { track: { loyalty: 1 } } },
        { label: '说活人不归你管，照单走', relation: -1, run: { track: { loyalty: 1, sin: 1 } } },
      ],
    },
    {
      id: 'bt-2',
      npc: 'ban-tou',
      stage: 2,
      act: 2,
      district: 'salvage',
      title: '班头：抽屉里的接管',
      text: '他把你领进值班室，拉开最下面那层抽屉：一支接管、一块编号牌、一张手写单，字是别人写的，签收栏空着。「这条手臂的主人还活着，在环带排队等排班。我把它拆下来的时候，接管还是温的。」他把手套摘了放在桌上，「巡检昨天来问过一次。你要想撇清，现在就可以走。」',
      when: { minFolded: 5, minRel: 2 },
      options: [
        { label: '替他把接管登记成报废件', relation: 3, run: { intel: 3, track: { sin: 2 } }, flag: 'bt_faked_scrap' },
        { label: '劝他把东西交出去止损', relation: 0, run: { track: { loyalty: 2, renown: -1 } } },
        { label: '说不掺和，转身就走', relation: -2, run: { intel: 1 } },
      ],
    },
    {
      id: 'bt-3',
      npc: 'ban-tou',
      stage: 3,
      act: 3,
      district: 'salvage',
      title: '班头：传送带停了',
      text: '传送带停了，场里安静得能听见管道里过水的声响。班头那副皮手套塞在抽屉边上，抽屉开着，接管还在原位。他说巡检今早拿走了设备日志，明天要跟编号比对。「我不求你保我，求你保这条。」他把接管推到你面前，「主人在环带，工号写在纸上。你把它还回去，怎么算账随你。」',
      when: { minFolded: 9 },
      options: [
        { label: '接下接管，答应还人', relation: 3, run: { intel: 3, track: { renown: 2, sin: 1 } }, flag: 'bt_returned_arm' },
        { label: '把接管上交，换他免罚', relation: -1, run: { money: 50, track: { loyalty: 2 } }, flag: 'bt_handed_in' },
        { label: '不接，让他自己交', relation: -2, run: { intel: 1, track: { sin: -1 } } },
      ],
    },

    /* ---------------- 无面 · 记忆银行柜员 · memory ---------------- */
    {
      id: 'wm-1',
      npc: 'wu-mian',
      stage: 1,
      act: 1,
      district: 'memory',
      title: '无面：取号三十七',
      text: '记忆银行的柜台是冷的，玻璃后面只亮着一盏斜面灯。无面接过你的号单，读了上面的编号，又读了一遍。「三十七号，登记用途是企业核查。」它把单子翻过来，在背面写了一行字，推回给你，「这行不属于本次核查，无面只是照着抄的。你来的时候，门口是不是有人在等你。」',
      when: { minFolded: 2 },
      options: [
        { label: '承认门口是有人等过', relation: 2, run: { intel: 3 }, flag: 'wm_admitted' },
        { label: '反问它抄的是谁的档案', relation: 1, run: { intel: 3, track: { sin: 1 } } },
        { label: '说没有，把单子推回去', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'wm-2',
      npc: 'wu-mian',
      stage: 2,
      act: 2,
      district: 'memory',
      title: '无面：不属于它的一段',
      text: '它把调阅记录摊在柜台上，最上面是你上次那张单子背面那行字的影印件。「无面归档时发现一段记忆，归属人是三十七号。」它说这句话时用了第三人称，「但那段记忆里的手不是无面的手，温度也不对。柜员没有温度。」它抬起头，「你能不能替无面看一眼，那段记忆里站在门口的人，是不是你。」',
      when: { minFolded: 5, minRel: 2 },
      options: [
        { label: '承认那段记忆里是自己', relation: 2, run: { intel: 4, track: { sin: 1 } }, flag: 'wm_confirmed' },
        { label: '要求调出完整档案', relation: 1, run: { intel: 4, track: { loyalty: -1 } } },
        { label: '说柜员的事与你无关', relation: -1, run: { track: { loyalty: 1 } } },
      ],
    },
    {
      id: 'wm-3',
      npc: 'wu-mian',
      stage: 3,
      act: 3,
      district: 'memory',
      title: '无面：它要把它取出来',
      text: '斜面灯坏了一格，柜台暗下去半边。无面把一段记忆的编号写在一张手写单上推过来：「三十七号。归属人写着无面，可无面不记得存过。」它停了一下，「按规程，不属于柜员的记忆要当场抹除；按无面想做的，是把它取出来交给你。你替它选一个，无面不问理由，也不留记录。」',
      when: { minFolded: 9 },
      options: [
        { label: '让它取出来，你带走', relation: 3, run: { intel: 4, track: { sin: 2, renown: 1 } }, flag: 'wm_extracted' },
        { label: '让它按规程当场抹除', relation: -2, run: { track: { loyalty: 3 } }, flag: 'wm_erased' },
        { label: '不替它选，让它自己定', relation: 1, run: { intel: 2, track: { sin: -1 } } },
      ],
    },
  ];
})();
